"""BatchNorm3d: expanded primitive implementation for BatchNorm3d:train.

Configuration: training=True; output and gradient comparison only; persistent buffer updates assessed separately
Limitations: Forward tensor may lower via NORM after axis reshaping, but running_mean/running_var/num_batches_tracked updates are not represented.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ...graph import TensorSpec
from .._support import ExpandedModule, ExpandedParameterDefinition


class BatchNorm3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'BatchNorm3d'
    source_repr = 'BatchNorm3d(4, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)'
    source_configuration = (('', 'torch.nn.modules.batchnorm', 'BatchNorm3d', (('affine', True), ('eps', 1e-05), ('momentum', 0.1), ('num_features', 4), ('track_running_stats', True), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 4, 3, 3, 3), torch.float64, torch.device('cpu')),)
    stateless = True

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class BatchNorm3d(ExpandedModule):
    definition_type = BatchNorm3dParameterDefinition

    def forward(self, x):
        # PERMUTE -> (4, 2, 3, 3, 3)
        node_1 = d.permute(x, (1, 0, 2, 3, 4))
        # RESHAPE -> (4, 54)
        node_2 = d.reshape(node_1, (4, -1))
        # NORM -> (4, 54)
        node_3 = d.norm(node_2, eps=1e-05)
        # RESHAPE -> (4, 2, 3, 3, 3)
        node_4 = d.reshape(node_3, (4, 2, 3, 3, 3))
        # PERMUTE -> (2, 4, 3, 3, 3)
        node_5 = d.permute(node_4, (1, 0, 2, 3, 4))
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_6 = d.reshape(self.p.param_weight, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_8 = d.broadcast(node_6, (2, 4, 3, 3, 3))
        # MUL -> (2, 4, 3, 3, 3)
        node_9 = d.mul(node_5, node_8)
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_10 = d.reshape(self.p.param_bias, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_12 = d.broadcast(node_10, (2, 4, 3, 3, 3))
        # ADD -> (2, 4, 3, 3, 3)
        node_13 = d.add(node_9, node_12)
        return node_13
