"""GELU: expanded primitive implementation for GELU:tanh.

Configuration: tanh approximation
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ...graph import TensorSpec
from .._support import ExpandedModule, ExpandedParameterDefinition


class GELUParameterDefinition(ExpandedParameterDefinition):
    public_name = 'GELU'
    source_repr = "GELU(approximate='tanh')"
    source_configuration = (('', 'torch.nn.modules.activation', 'GELU', (('approximate', 'tanh'), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_4: shape=(), dtype=torch.float64
        self.register_buffer('constant_4', torch.tensor(
            0.044715,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_8: shape=(), dtype=torch.float64
        self.register_buffer('constant_8', torch.tensor(
            0.7978845608028654,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_11: shape=(), dtype=torch.float64
        self.register_buffer('constant_11', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_16: shape=(), dtype=torch.float64
        self.register_buffer('constant_16', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))


class GELU(ExpandedModule):
    definition_type = GELUParameterDefinition

    def forward(self, x):
        # MUL -> (2, 3)
        node_1 = d.mul(x, x)
        # MUL -> (2, 3)
        node_2 = d.mul(node_1, x)
        # BROADCAST -> (2, 3)
        node_3 = d.broadcast(self.p.constant_4, (2, 3))
        # MUL -> (2, 3)
        node_5 = d.mul(node_2, node_3)
        # ADD -> (2, 3)
        node_6 = d.add(x, node_5)
        # BROADCAST -> (2, 3)
        node_7 = d.broadcast(self.p.constant_8, (2, 3))
        # MUL -> (2, 3)
        node_9 = d.mul(node_6, node_7)
        # BROADCAST -> (2, 3)
        node_10 = d.broadcast(self.p.constant_11, (2, 3))
        # NONLINEAR -> (2, 3)
        node_12 = d.nonlinear(node_9, activation='tanh')
        # ADD -> (2, 3)
        node_13 = d.add(node_10, node_12)
        # MUL -> (2, 3)
        node_14 = d.mul(x, node_13)
        # BROADCAST -> (2, 3)
        node_15 = d.broadcast(self.p.constant_16, (2, 3))
        # MUL -> (2, 3)
        node_17 = d.mul(node_14, node_15)
        return node_17
