"""LazyInstanceNorm3d: expanded primitive implementation for LazyInstanceNorm3d:train.

Configuration: training=True; output and gradient comparison only; persistent buffer updates assessed separately
Limitations: Forward tensor may lower via NORM after axis reshaping, but running_mean/running_var/num_batches_tracked updates are not represented.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ...graph import TensorSpec
from .._support import ExpandedModule, ExpandedParameterDefinition


class LazyInstanceNorm3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LazyInstanceNorm3d'
    source_repr = 'InstanceNorm3d(4, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)'
    source_configuration = (('', 'torch.nn.modules.instancenorm', 'InstanceNorm3d', (('affine', True), ('eps', 1e-05), ('momentum', 0.1), ('num_features', 4), ('track_running_stats', True), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 4, 3, 3, 3), torch.float64, torch.device('cpu')),)
    stateless = True

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class LazyInstanceNorm3d(ExpandedModule):
    definition_type = LazyInstanceNorm3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 4, 27)
        node_1 = d.reshape(x, (2, 4, -1))
        # NORM -> (2, 4, 27)
        node_2 = d.norm(node_1, eps=1e-05)
        # RESHAPE -> (2, 4, 3, 3, 3)
        node_3 = d.reshape(node_2, (2, 4, 3, 3, 3))
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_4 = d.reshape(self.p.param_weight, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_6 = d.broadcast(node_4, (2, 4, 3, 3, 3))
        # MUL -> (2, 4, 3, 3, 3)
        node_7 = d.mul(node_3, node_6)
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_8 = d.reshape(self.p.param_bias, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_10 = d.broadcast(node_8, (2, 4, 3, 3, 3))
        # ADD -> (2, 4, 3, 3, 3)
        node_11 = d.add(node_7, node_10)
        return node_11
