"""LoopedCNN: expanded primitive implementation for LoopedCNN:shared3.

Configuration: same block/parameters repeated 3 times; max_steps=6
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ...graph import TensorSpec
from .._support import ExpandedModule, ExpandedParameterDefinition


class LoopedCNNParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LoopedCNN'
    source_repr = 'Sequential(\n  (0): Conv2d(2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n  (1): Conv2d(2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n  (2): Conv2d(2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n)'
    source_configuration = (('', 'torch.nn.modules.container', 'Sequential', (('training', False),)), ('0', 'torch.nn.modules.conv', 'Conv2d', (('dilation', (1, 1)), ('groups', 1), ('in_channels', 2), ('kernel_size', (3, 3)), ('out_channels', 2), ('output_padding', (0, 0)), ('padding', (1, 1)), ('padding_mode', 'zeros'), ('stride', (1, 1)), ('training', False), ('transposed', False))))
    frozen_buffers = {}
    source_modes = (('', False), ('0', False))
    input_specs = (TensorSpec((1, 2, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    domain_node_19 = {'axes': (2, 3), 'size': (3, 3), 'stride': (1, 1), 'dilation': (1, 1), 'padding': ((1, 1), (1, 1)), 'output_axis': -1, 'kind': 'window'}

    def __init__(self, source):
        super().__init__(source)
        # constant_8: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_8', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_12: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_12', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))

    @property
    def param_0_weight(self):
        return self.source[0].weight

    @property
    def param_0_bias(self):
        return self.source[0].bias


class LoopedCNN(ExpandedModule):
    definition_type = LoopedCNNParameterDefinition

    def forward(self, x):
        # REPEAT -> (1, 2, 4, 4)
        node_20 = d.LOOP.REPEAT(
            self.node_20_body,
            x,
            steps=3,
            max_steps=6,
            parameters={'mode': 'shared', 'values': {'weight': self.p.param_0_weight, 'bias': self.p.param_0_bias}},
            output='last',
        )
        return node_20

    def node_20_body(self, state, parameters):
        # SCAN -> ((1, 2, 4, 4), None)
        node_19 = d.LOOP.SCAN(
            self.node_19_body,
            state,
            None,
            domain=self.p.domain_node_19,
            parameters={'mode': 'shared', 'values': {'weight': parameters['weight'], 'bias': parameters['bias']}},
        )
        return node_19[0]

    def node_19_body(self, fragment, carry, parameters):
        # ROUTE -> (1, 2, 3, 3)
        node_7 = d.route(fragment, self.p.constant_8, dim=1)
        # PERMUTE -> (1, 3, 3, 2)
        node_9 = d.permute(node_7, (0, 2, 3, 1))
        # RESHAPE -> (1, 18)
        node_10 = d.reshape(node_9, (1, -1))
        # ROUTE -> (2, 2, 3, 3)
        node_11 = d.route(parameters['weight'], self.p.constant_12, dim=0)
        # PERMUTE -> (3, 3, 2, 2)
        node_13 = d.permute(node_11, (2, 3, 1, 0))
        # RESHAPE -> (18, 2)
        node_14 = d.reshape(node_13, (18, 2))
        # PROJECT -> (1, 2)
        node_15 = d.project(node_10, node_14)
        # CONCAT -> (1, 2)
        node_16 = d.concat([node_15], dim=-1)
        # BROADCAST -> (1, 2)
        node_17 = d.broadcast(parameters['bias'], (1, 2))
        # ADD -> (1, 2)
        node_18 = d.add(node_16, node_17)
        return (node_18, None)
