"""TransformerEncoderLayer: expanded primitive implementation for TransformerEncoderLayer:pre_norm.

Configuration: pre-norm; no masks/dropout
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ...graph import TensorSpec
from .._support import ExpandedModule, ExpandedParameterDefinition


class TransformerEncoderLayerParameterDefinition(ExpandedParameterDefinition):
    public_name = 'TransformerEncoderLayer'
    source_repr = 'TransformerEncoderLayer(\n  (self_attn): MultiheadAttention(\n    (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)\n  )\n  (linear1): Linear(in_features=8, out_features=12, bias=True)\n  (dropout): Dropout(p=0, inplace=False)\n  (linear2): Linear(in_features=12, out_features=8, bias=True)\n  (norm1): LayerNorm((8,), eps=1e-05, elementwise_affine=True, bias=True)\n  (norm2): LayerNorm((8,), eps=1e-05, elementwise_affine=True, bias=True)\n  (dropout1): Dropout(p=0, inplace=False)\n  (dropout2): Dropout(p=0, inplace=False)\n)'
    source_configuration = (('', 'torch.nn.modules.transformer', 'TransformerEncoderLayer', (('activation', 'torch.nn.functional.relu'), ('activation_relu_or_gelu', 1), ('norm_first', True), ('training', False))), ('self_attn', 'torch.nn.modules.activation', 'MultiheadAttention', (('add_zero_attn', False), ('batch_first', True), ('bias_k', None), ('bias_v', None), ('dropout', 0), ('embed_dim', 8), ('head_dim', 4), ('kdim', 8), ('num_heads', 2), ('training', False), ('vdim', 8))), ('self_attn.out_proj', 'torch.nn.modules.linear', 'NonDynamicallyQuantizableLinear', (('in_features', 8), ('out_features', 8), ('training', False))), ('linear1', 'torch.nn.modules.linear', 'Linear', (('in_features', 8), ('out_features', 12), ('training', False))), ('dropout', 'torch.nn.modules.dropout', 'Dropout', (('inplace', False), ('p', 0), ('training', False))), ('linear2', 'torch.nn.modules.linear', 'Linear', (('in_features', 12), ('out_features', 8), ('training', False))), ('norm1', 'torch.nn.modules.normalization', 'LayerNorm', (('elementwise_affine', True), ('eps', 1e-05), ('normalized_shape', (8,)), ('training', False))), ('norm2', 'torch.nn.modules.normalization', 'LayerNorm', (('elementwise_affine', True), ('eps', 1e-05), ('normalized_shape', (8,)), ('training', False))), ('dropout1', 'torch.nn.modules.dropout', 'Dropout', (('inplace', False), ('p', 0), ('training', False))), ('dropout2', 'torch.nn.modules.dropout', 'Dropout', (('inplace', False), ('p', 0), ('training', False))))
    frozen_buffers = {}
    source_modes = (('', False), ('self_attn', False), ('self_attn.out_proj', False), ('linear1', False), ('dropout', False), ('linear2', False), ('norm1', False), ('norm2', False), ('dropout1', False), ('dropout2', False))
    input_specs = (TensorSpec((2, 3, 8), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_6: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_8: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_8', torch.tensor(
            [8, 9, 10, 11, 12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_10: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_10', torch.tensor(
            [16, 17, 18, 19, 20, 21, 22, 23],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_13: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_13', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_15: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [8, 9, 10, 11, 12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_17: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_17', torch.tensor(
            [16, 17, 18, 19, 20, 21, 22, 23],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_38: shape=(), dtype=torch.float64
        self.register_buffer('constant_38', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))

    @property
    def param_norm1_weight(self):
        return self.source.norm1.weight

    @property
    def param_norm1_bias(self):
        return self.source.norm1.bias

    @property
    def param_self_attn_in_proj_weight(self):
        return self.source.self_attn.in_proj_weight

    @property
    def param_self_attn_in_proj_bias(self):
        return self.source.self_attn.in_proj_bias

    @property
    def param_self_attn_out_proj_weight(self):
        return self.source.self_attn.out_proj.weight

    @property
    def param_self_attn_out_proj_bias(self):
        return self.source.self_attn.out_proj.bias

    @property
    def param_norm2_weight(self):
        return self.source.norm2.weight

    @property
    def param_norm2_bias(self):
        return self.source.norm2.bias

    @property
    def param_linear1_weight(self):
        return self.source.linear1.weight

    @property
    def param_linear1_bias(self):
        return self.source.linear1.bias

    @property
    def param_linear2_weight(self):
        return self.source.linear2.weight

    @property
    def param_linear2_bias(self):
        return self.source.linear2.bias


class TransformerEncoderLayer(ExpandedModule):
    definition_type = TransformerEncoderLayerParameterDefinition

    def forward(self, x):
        # NORM -> (2, 3, 8)
        node_1 = d.norm(x, normalized_shape=(8,), weight=self.p.param_norm1_weight, bias=self.p.param_norm1_bias, eps=1e-05)
        # ROUTE -> (8, 8)
        node_4 = d.route(self.p.param_self_attn_in_proj_weight, self.p.constant_6, dim=0)
        # ROUTE -> (8, 8)
        node_7 = d.route(self.p.param_self_attn_in_proj_weight, self.p.constant_8, dim=0)
        # ROUTE -> (8, 8)
        node_9 = d.route(self.p.param_self_attn_in_proj_weight, self.p.constant_10, dim=0)
        # ROUTE -> (8,)
        node_11 = d.route(self.p.param_self_attn_in_proj_bias, self.p.constant_13, dim=0)
        # ROUTE -> (8,)
        node_14 = d.route(self.p.param_self_attn_in_proj_bias, self.p.constant_15, dim=0)
        # ROUTE -> (8,)
        node_16 = d.route(self.p.param_self_attn_in_proj_bias, self.p.constant_17, dim=0)
        # PERMUTE -> (8, 8)
        node_18 = d.permute(node_4, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_19 = d.project(node_1, node_18)
        # BROADCAST -> (2, 3, 8)
        node_20 = d.broadcast(node_11, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_21 = d.add(node_19, node_20)
        # PERMUTE -> (8, 8)
        node_22 = d.permute(node_7, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_23 = d.project(node_1, node_22)
        # BROADCAST -> (2, 3, 8)
        node_24 = d.broadcast(node_14, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_25 = d.add(node_23, node_24)
        # PERMUTE -> (8, 8)
        node_26 = d.permute(node_9, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_27 = d.project(node_1, node_26)
        # BROADCAST -> (2, 3, 8)
        node_28 = d.broadcast(node_16, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_29 = d.add(node_27, node_28)
        # RESHAPE -> (2, 3, 2, 4)
        node_30 = d.reshape(node_21, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_31 = d.permute(node_30, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 2, 4)
        node_32 = d.reshape(node_25, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_33 = d.permute(node_32, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 2, 4)
        node_34 = d.reshape(node_29, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_35 = d.permute(node_34, (0, 2, 1, 3))
        # COMPARE -> (2, 2, 3, 3)
        node_36 = d.compare(node_31, node_33)
        # BROADCAST -> (2, 2, 3, 3)
        node_37 = d.broadcast(self.p.constant_38, (2, 2, 3, 3))
        # MUL -> (2, 2, 3, 3)
        node_39 = d.mul(node_36, node_37)
        # NORMALIZE -> (2, 2, 3, 3)
        node_40 = d.normalize(node_39)
        # MIX -> (2, 2, 3, 4)
        node_41 = d.mix(node_35, node_40)
        # PERMUTE -> (2, 3, 2, 4)
        node_42 = d.permute(node_41, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 8)
        node_43 = d.reshape(node_42, (2, 3, 8))
        # PERMUTE -> (8, 8)
        node_44 = d.permute(self.p.param_self_attn_out_proj_weight, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_46 = d.project(node_43, node_44)
        # BROADCAST -> (2, 3, 8)
        node_47 = d.broadcast(self.p.param_self_attn_out_proj_bias, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_49 = d.add(node_46, node_47)
        # REDUCE -> (2, 3, 3)
        node_50 = d.reduce(node_40, dim=1, reducer='mean')
        # ADD -> (2, 3, 8)
        node_51 = d.add(x, node_49)
        # NORM -> (2, 3, 8)
        node_52 = d.norm(node_51, normalized_shape=(8,), weight=self.p.param_norm2_weight, bias=self.p.param_norm2_bias, eps=1e-05)
        # PERMUTE -> (8, 12)
        node_55 = d.permute(self.p.param_linear1_weight, (1, 0))
        # PROJECT -> (2, 3, 12)
        node_57 = d.project(node_52, node_55)
        # BROADCAST -> (2, 3, 12)
        node_58 = d.broadcast(self.p.param_linear1_bias, (2, 3, 12))
        # ADD -> (2, 3, 12)
        node_60 = d.add(node_57, node_58)
        # NONLINEAR -> (2, 3, 12)
        node_61 = d.nonlinear(node_60)
        # PERMUTE -> (12, 8)
        node_62 = d.permute(self.p.param_linear2_weight, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_64 = d.project(node_61, node_62)
        # BROADCAST -> (2, 3, 8)
        node_65 = d.broadcast(self.p.param_linear2_bias, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_67 = d.add(node_64, node_65)
        # ADD -> (2, 3, 8)
        node_68 = d.add(node_51, node_67)
        return node_68
