"""AdaptiveMaxPool2d: expanded primitive implementation for AdaptiveMaxPool2d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: Max values only; argmax indices and tie-gradient semantics are not covered.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class AdaptiveMaxPool2dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'AdaptiveMaxPool2d'
    source_repr = 'AdaptiveMaxPool2d(output_size=2)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'AdaptiveMaxPool2d', (('output_size', 2), ('return_indices', False), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(9,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 2, 5, 6, 7, 10, 11, 12],
            dtype=torch.int64, device='cpu').reshape((9,)))
        # constant_6: shape=(9,), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [2, 3, 4, 7, 8, 9, 12, 13, 14],
            dtype=torch.int64, device='cpu').reshape((9,)))
        # constant_9: shape=(9,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [10, 11, 12, 15, 16, 17, 20, 21, 22],
            dtype=torch.int64, device='cpu').reshape((9,)))
        # constant_12: shape=(9,), dtype=torch.int64
        self.register_buffer('constant_12', torch.tensor(
            [12, 13, 14, 17, 18, 19, 22, 23, 24],
            dtype=torch.int64, device='cpu').reshape((9,)))


class AdaptiveMaxPool2d(ExpandedModule):
    definition_type = AdaptiveMaxPool2dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 25)
        node_1 = d.reshape(x, (2, 3, 25))
        # ROUTE -> (2, 3, 9)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 9)
        node_5 = d.route(node_1, self.p.constant_6, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_7 = d.reduce(node_5, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 9)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 9)
        node_11 = d.route(node_1, self.p.constant_12, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_13 = d.reduce(node_11, dim=-1, reducer='max', keepdim=True)
        # CONCAT -> (2, 3, 4)
        node_14 = d.concat([node_4, node_7, node_10, node_13], dim=-1)
        # RESHAPE -> (2, 3, 2, 2)
        node_15 = d.reshape(node_14, (2, 3, 2, 2))
        return node_15
