"""AdaptiveAvgPool1d: expanded primitive implementation for AdaptiveAvgPool1d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class AdaptiveAvgPool1dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'AdaptiveAvgPool1d'
    source_repr = 'AdaptiveAvgPool1d(output_size=2)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'AdaptiveAvgPool1d', (('output_size', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(3,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 2],
            dtype=torch.int64, device='cpu').reshape((3,)))
        # constant_6: shape=(), dtype=torch.float64
        self.register_buffer('constant_6', torch.tensor(
            0.3333333333333333,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(3,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [2, 3, 4],
            dtype=torch.int64, device='cpu').reshape((3,)))
        # constant_12: shape=(), dtype=torch.float64
        self.register_buffer('constant_12', torch.tensor(
            0.3333333333333333,
            dtype=torch.float64, device='cpu').reshape(()))


class AdaptiveAvgPool1d(ExpandedModule):
    definition_type = AdaptiveAvgPool1dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 5)
        node_1 = d.reshape(x, (2, 3, 5))
        # ROUTE -> (2, 3, 3)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_5 = d.broadcast(self.p.constant_6, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_7 = d.mul(node_4, node_5)
        # ROUTE -> (2, 3, 3)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_11 = d.broadcast(self.p.constant_12, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_13 = d.mul(node_10, node_11)
        # CONCAT -> (2, 3, 2)
        node_14 = d.concat([node_7, node_13], dim=-1)
        # RESHAPE -> (2, 3, 2)
        node_15 = d.reshape(node_14, (2, 3, 2))
        return node_15
