"""AdaptiveMaxPool3d: expanded primitive implementation for AdaptiveMaxPool3d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: Max values only; argmax indices and tie-gradient semantics are not covered.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class AdaptiveMaxPool3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'AdaptiveMaxPool3d'
    source_repr = 'AdaptiveMaxPool3d(output_size=2)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'AdaptiveMaxPool3d', (('output_size', 2), ('return_indices', False), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 2, 5, 6, 7, 10, 11, 12, 25, 26, 27, 30, 31, 32, 35, 36, 37, 50, 51, 52, 55, 56, 57,
             60, 61, 62],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_6: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [2, 3, 4, 7, 8, 9, 12, 13, 14, 27, 28, 29, 32, 33, 34, 37, 38, 39, 52, 53, 54, 57, 58, 59,
             62, 63, 64],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_9: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [10, 11, 12, 15, 16, 17, 20, 21, 22, 35, 36, 37, 40, 41, 42, 45, 46, 47, 60, 61, 62, 65,
             66, 67, 70, 71, 72],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_12: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_12', torch.tensor(
            [12, 13, 14, 17, 18, 19, 22, 23, 24, 37, 38, 39, 42, 43, 44, 47, 48, 49, 62, 63, 64, 67,
             68, 69, 72, 73, 74],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_15: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [50, 51, 52, 55, 56, 57, 60, 61, 62, 75, 76, 77, 80, 81, 82, 85, 86, 87, 100, 101, 102,
             105, 106, 107, 110, 111, 112],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_18: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_18', torch.tensor(
            [52, 53, 54, 57, 58, 59, 62, 63, 64, 77, 78, 79, 82, 83, 84, 87, 88, 89, 102, 103, 104,
             107, 108, 109, 112, 113, 114],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_21: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [60, 61, 62, 65, 66, 67, 70, 71, 72, 85, 86, 87, 90, 91, 92, 95, 96, 97, 110, 111, 112,
             115, 116, 117, 120, 121, 122],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_24: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_24', torch.tensor(
            [62, 63, 64, 67, 68, 69, 72, 73, 74, 87, 88, 89, 92, 93, 94, 97, 98, 99, 112, 113, 114,
             117, 118, 119, 122, 123, 124],
            dtype=torch.int64, device='cpu').reshape((27,)))


class AdaptiveMaxPool3d(ExpandedModule):
    definition_type = AdaptiveMaxPool3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 125)
        node_1 = d.reshape(x, (2, 3, 125))
        # ROUTE -> (2, 3, 27)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_5 = d.route(node_1, self.p.constant_6, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_7 = d.reduce(node_5, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_11 = d.route(node_1, self.p.constant_12, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_13 = d.reduce(node_11, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_14 = d.route(node_1, self.p.constant_15, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_16 = d.reduce(node_14, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_17 = d.route(node_1, self.p.constant_18, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_19 = d.reduce(node_17, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_20 = d.route(node_1, self.p.constant_21, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_22 = d.reduce(node_20, dim=-1, reducer='max', keepdim=True)
        # ROUTE -> (2, 3, 27)
        node_23 = d.route(node_1, self.p.constant_24, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_25 = d.reduce(node_23, dim=-1, reducer='max', keepdim=True)
        # CONCAT -> (2, 3, 8)
        node_26 = d.concat([node_4, node_7, node_10, node_13, node_16, node_19, node_22, node_25], dim=-1)
        # RESHAPE -> (2, 3, 2, 2, 2)
        node_27 = d.reshape(node_26, (2, 3, 2, 2, 2))
        return node_27
