"""AdaptiveAvgPool3d: expanded primitive implementation for AdaptiveAvgPool3d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class AdaptiveAvgPool3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'AdaptiveAvgPool3d'
    source_repr = 'AdaptiveAvgPool3d(output_size=2)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'AdaptiveAvgPool3d', (('output_size', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 2, 5, 6, 7, 10, 11, 12, 25, 26, 27, 30, 31, 32, 35, 36, 37, 50, 51, 52, 55, 56, 57,
             60, 61, 62],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_6: shape=(), dtype=torch.float64
        self.register_buffer('constant_6', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [2, 3, 4, 7, 8, 9, 12, 13, 14, 27, 28, 29, 32, 33, 34, 37, 38, 39, 52, 53, 54, 57, 58, 59,
             62, 63, 64],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_12: shape=(), dtype=torch.float64
        self.register_buffer('constant_12', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_15: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [10, 11, 12, 15, 16, 17, 20, 21, 22, 35, 36, 37, 40, 41, 42, 45, 46, 47, 60, 61, 62, 65,
             66, 67, 70, 71, 72],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_18: shape=(), dtype=torch.float64
        self.register_buffer('constant_18', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_21: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [12, 13, 14, 17, 18, 19, 22, 23, 24, 37, 38, 39, 42, 43, 44, 47, 48, 49, 62, 63, 64, 67,
             68, 69, 72, 73, 74],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_24: shape=(), dtype=torch.float64
        self.register_buffer('constant_24', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_27: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_27', torch.tensor(
            [50, 51, 52, 55, 56, 57, 60, 61, 62, 75, 76, 77, 80, 81, 82, 85, 86, 87, 100, 101, 102,
             105, 106, 107, 110, 111, 112],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_30: shape=(), dtype=torch.float64
        self.register_buffer('constant_30', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_33: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_33', torch.tensor(
            [52, 53, 54, 57, 58, 59, 62, 63, 64, 77, 78, 79, 82, 83, 84, 87, 88, 89, 102, 103, 104,
             107, 108, 109, 112, 113, 114],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_36: shape=(), dtype=torch.float64
        self.register_buffer('constant_36', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_39: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_39', torch.tensor(
            [60, 61, 62, 65, 66, 67, 70, 71, 72, 85, 86, 87, 90, 91, 92, 95, 96, 97, 110, 111, 112,
             115, 116, 117, 120, 121, 122],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_42: shape=(), dtype=torch.float64
        self.register_buffer('constant_42', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_45: shape=(27,), dtype=torch.int64
        self.register_buffer('constant_45', torch.tensor(
            [62, 63, 64, 67, 68, 69, 72, 73, 74, 87, 88, 89, 92, 93, 94, 97, 98, 99, 112, 113, 114,
             117, 118, 119, 122, 123, 124],
            dtype=torch.int64, device='cpu').reshape((27,)))
        # constant_48: shape=(), dtype=torch.float64
        self.register_buffer('constant_48', torch.tensor(
            0.037037037037037035,
            dtype=torch.float64, device='cpu').reshape(()))


class AdaptiveAvgPool3d(ExpandedModule):
    definition_type = AdaptiveAvgPool3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 125)
        node_1 = d.reshape(x, (2, 3, 125))
        # ROUTE -> (2, 3, 27)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_5 = d.broadcast(self.p.constant_6, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_7 = d.mul(node_4, node_5)
        # ROUTE -> (2, 3, 27)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_11 = d.broadcast(self.p.constant_12, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_13 = d.mul(node_10, node_11)
        # ROUTE -> (2, 3, 27)
        node_14 = d.route(node_1, self.p.constant_15, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_16 = d.reduce(node_14, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_17 = d.broadcast(self.p.constant_18, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_19 = d.mul(node_16, node_17)
        # ROUTE -> (2, 3, 27)
        node_20 = d.route(node_1, self.p.constant_21, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_22 = d.reduce(node_20, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_23 = d.broadcast(self.p.constant_24, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_25 = d.mul(node_22, node_23)
        # ROUTE -> (2, 3, 27)
        node_26 = d.route(node_1, self.p.constant_27, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_28 = d.reduce(node_26, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_29 = d.broadcast(self.p.constant_30, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_31 = d.mul(node_28, node_29)
        # ROUTE -> (2, 3, 27)
        node_32 = d.route(node_1, self.p.constant_33, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_34 = d.reduce(node_32, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_35 = d.broadcast(self.p.constant_36, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_37 = d.mul(node_34, node_35)
        # ROUTE -> (2, 3, 27)
        node_38 = d.route(node_1, self.p.constant_39, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_40 = d.reduce(node_38, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_41 = d.broadcast(self.p.constant_42, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_43 = d.mul(node_40, node_41)
        # ROUTE -> (2, 3, 27)
        node_44 = d.route(node_1, self.p.constant_45, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_46 = d.reduce(node_44, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_47 = d.broadcast(self.p.constant_48, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_49 = d.mul(node_46, node_47)
        # CONCAT -> (2, 3, 8)
        node_50 = d.concat([node_7, node_13, node_19, node_25, node_31, node_37, node_43, node_49], dim=-1)
        # RESHAPE -> (2, 3, 2, 2, 2)
        node_51 = d.reshape(node_50, (2, 3, 2, 2, 2))
        return node_51
