"""AvgPool3d: expanded primitive implementation for AvgPool3d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class AvgPool3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'AvgPool3d'
    source_repr = 'AvgPool3d(kernel_size=2, stride=2, padding=0)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'AvgPool3d', (('ceil_mode', False), ('count_include_pad', True), ('divisor_override', None), ('kernel_size', 2), ('padding', 0), ('stride', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 5, 6, 25, 26, 30, 31],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_6: shape=(), dtype=torch.float64
        self.register_buffer('constant_6', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [2, 3, 7, 8, 27, 28, 32, 33],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_12: shape=(), dtype=torch.float64
        self.register_buffer('constant_12', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_15: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [10, 11, 15, 16, 35, 36, 40, 41],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_18: shape=(), dtype=torch.float64
        self.register_buffer('constant_18', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_21: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [12, 13, 17, 18, 37, 38, 42, 43],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_24: shape=(), dtype=torch.float64
        self.register_buffer('constant_24', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_27: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_27', torch.tensor(
            [50, 51, 55, 56, 75, 76, 80, 81],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_30: shape=(), dtype=torch.float64
        self.register_buffer('constant_30', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_33: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_33', torch.tensor(
            [52, 53, 57, 58, 77, 78, 82, 83],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_36: shape=(), dtype=torch.float64
        self.register_buffer('constant_36', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_39: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_39', torch.tensor(
            [60, 61, 65, 66, 85, 86, 90, 91],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_42: shape=(), dtype=torch.float64
        self.register_buffer('constant_42', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_45: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_45', torch.tensor(
            [62, 63, 67, 68, 87, 88, 92, 93],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_48: shape=(), dtype=torch.float64
        self.register_buffer('constant_48', torch.tensor(
            0.125,
            dtype=torch.float64, device='cpu').reshape(()))


class AvgPool3d(ExpandedModule):
    definition_type = AvgPool3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 125)
        node_1 = d.reshape(x, (2, 3, 125))
        # ROUTE -> (2, 3, 8)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_5 = d.broadcast(self.p.constant_6, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_7 = d.mul(node_4, node_5)
        # ROUTE -> (2, 3, 8)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_11 = d.broadcast(self.p.constant_12, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_13 = d.mul(node_10, node_11)
        # ROUTE -> (2, 3, 8)
        node_14 = d.route(node_1, self.p.constant_15, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_16 = d.reduce(node_14, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_17 = d.broadcast(self.p.constant_18, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_19 = d.mul(node_16, node_17)
        # ROUTE -> (2, 3, 8)
        node_20 = d.route(node_1, self.p.constant_21, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_22 = d.reduce(node_20, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_23 = d.broadcast(self.p.constant_24, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_25 = d.mul(node_22, node_23)
        # ROUTE -> (2, 3, 8)
        node_26 = d.route(node_1, self.p.constant_27, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_28 = d.reduce(node_26, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_29 = d.broadcast(self.p.constant_30, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_31 = d.mul(node_28, node_29)
        # ROUTE -> (2, 3, 8)
        node_32 = d.route(node_1, self.p.constant_33, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_34 = d.reduce(node_32, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_35 = d.broadcast(self.p.constant_36, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_37 = d.mul(node_34, node_35)
        # ROUTE -> (2, 3, 8)
        node_38 = d.route(node_1, self.p.constant_39, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_40 = d.reduce(node_38, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_41 = d.broadcast(self.p.constant_42, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_43 = d.mul(node_40, node_41)
        # ROUTE -> (2, 3, 8)
        node_44 = d.route(node_1, self.p.constant_45, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_46 = d.reduce(node_44, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_47 = d.broadcast(self.p.constant_48, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_49 = d.mul(node_46, node_47)
        # CONCAT -> (2, 3, 8)
        node_50 = d.concat([node_7, node_13, node_19, node_25, node_31, node_37, node_43, node_49], dim=-1)
        # RESHAPE -> (2, 3, 2, 2, 2)
        node_51 = d.reshape(node_50, (2, 3, 2, 2, 2))
        return node_51
