"""AvgPool2d: expanded primitive implementation for AvgPool2d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class AvgPool2dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'AvgPool2d'
    source_repr = 'AvgPool2d(kernel_size=2, stride=2, padding=0)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'AvgPool2d', (('ceil_mode', False), ('count_include_pad', True), ('divisor_override', None), ('kernel_size', 2), ('padding', 0), ('stride', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 5, 6],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_6: shape=(), dtype=torch.float64
        self.register_buffer('constant_6', torch.tensor(
            0.25,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [2, 3, 7, 8],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_12: shape=(), dtype=torch.float64
        self.register_buffer('constant_12', torch.tensor(
            0.25,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_15: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [10, 11, 15, 16],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_18: shape=(), dtype=torch.float64
        self.register_buffer('constant_18', torch.tensor(
            0.25,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_21: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [12, 13, 17, 18],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_24: shape=(), dtype=torch.float64
        self.register_buffer('constant_24', torch.tensor(
            0.25,
            dtype=torch.float64, device='cpu').reshape(()))


class AvgPool2d(ExpandedModule):
    definition_type = AvgPool2dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 25)
        node_1 = d.reshape(x, (2, 3, 25))
        # ROUTE -> (2, 3, 4)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_5 = d.broadcast(self.p.constant_6, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_7 = d.mul(node_4, node_5)
        # ROUTE -> (2, 3, 4)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_11 = d.broadcast(self.p.constant_12, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_13 = d.mul(node_10, node_11)
        # ROUTE -> (2, 3, 4)
        node_14 = d.route(node_1, self.p.constant_15, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_16 = d.reduce(node_14, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_17 = d.broadcast(self.p.constant_18, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_19 = d.mul(node_16, node_17)
        # ROUTE -> (2, 3, 4)
        node_20 = d.route(node_1, self.p.constant_21, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_22 = d.reduce(node_20, dim=-1, reducer='sum', keepdim=True)
        # BROADCAST -> (2, 3, 1)
        node_23 = d.broadcast(self.p.constant_24, (2, 3, 1))
        # MUL -> (2, 3, 1)
        node_25 = d.mul(node_22, node_23)
        # CONCAT -> (2, 3, 4)
        node_26 = d.concat([node_7, node_13, node_19, node_25], dim=-1)
        # RESHAPE -> (2, 3, 2, 2)
        node_27 = d.reshape(node_26, (2, 3, 2, 2))
        return node_27
