"""Bilinear: expanded primitive implementation for Bilinear.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class BilinearParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Bilinear'
    source_repr = 'Bilinear(in1_features=3, in2_features=4, out_features=2, bias=True)'
    source_configuration = (('', 'torch.nn.modules.linear', 'Bilinear', (('in1_features', 3), ('in2_features', 4), ('out_features', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 4), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_4: shape=(1,), dtype=torch.int64
        self.register_buffer('constant_4', torch.tensor(
            [0],
            dtype=torch.int64, device='cpu').reshape((1,)))
        # constant_10: shape=(1,), dtype=torch.int64
        self.register_buffer('constant_10', torch.tensor(
            [1],
            dtype=torch.int64, device='cpu').reshape((1,)))

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class Bilinear(ExpandedModule):
    definition_type = BilinearParameterDefinition

    def forward(self, x, y):
        # ROUTE -> (1, 3, 4)
        node_2 = d.route(self.p.param_weight, self.p.constant_4, dim=0)
        # RESHAPE -> (3, 4)
        node_5 = d.reshape(node_2, [3, 4])
        # PROJECT -> (2, 4)
        node_6 = d.project(x, node_5)
        # MUL -> (2, 4)
        node_7 = d.mul(node_6, y)
        # REDUCE -> (2, 1)
        node_8 = d.reduce(node_7, dim=-1, keepdim=True)
        # ROUTE -> (1, 3, 4)
        node_9 = d.route(self.p.param_weight, self.p.constant_10, dim=0)
        # RESHAPE -> (3, 4)
        node_11 = d.reshape(node_9, [3, 4])
        # PROJECT -> (2, 4)
        node_12 = d.project(x, node_11)
        # MUL -> (2, 4)
        node_13 = d.mul(node_12, y)
        # REDUCE -> (2, 1)
        node_14 = d.reduce(node_13, dim=-1, keepdim=True)
        # CONCAT -> (2, 2)
        node_15 = d.concat([node_8, node_14], dim=-1)
        # BROADCAST -> (2, 2)
        node_16 = d.broadcast(self.p.param_bias, (2, 2))
        # ADD -> (2, 2)
        node_18 = d.add(node_15, node_16)
        return node_18
