"""ConstantPad1d: expanded primitive implementation for ConstantPad1d.

Configuration: asymmetric positive padding (1,2) per axis
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ConstantPad1dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ConstantPad1d'
    source_repr = 'ConstantPad1d(padding=(1, 2), value=0.25)'
    source_configuration = (('', 'torch.nn.modules.padding', 'ConstantPad1d', (('padding', (1, 2)), ('training', True), ('value', 0.25))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(7,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [-1, 0, 1, 2, 3, -1, -1],
            dtype=torch.int64, device='cpu').reshape((7,)))
        # constant_5: shape=(7,), dtype=torch.float64
        self.register_buffer('constant_5', torch.tensor(
            [0.25, 0.0, 0.0, 0.0, 0.0, 0.25, 0.25],
            dtype=torch.float64, device='cpu').reshape((7,)))


class ConstantPad1d(ExpandedModule):
    definition_type = ConstantPad1dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 4)
        node_1 = d.reshape(x, (2, 3, 4))
        # ROUTE -> (2, 3, 7)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # BROADCAST -> (2, 3, 7)
        node_4 = d.broadcast(self.p.constant_5, (2, 3, 7))
        # ADD -> (2, 3, 7)
        node_6 = d.add(node_2, node_4)
        # RESHAPE -> (2, 3, 7)
        node_7 = d.reshape(node_6, (2, 3, 7))
        return node_7
