"""Conv3d: expanded primitive implementation for Conv3d.

Configuration: groups=2, stride=2, padding=1, kernel=3; transposed output_padding=1; lazy materialized
Limitations: Only dense real kernels; padding_mode=zeros. No complex input, parametrization or lazy initialization semantics.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class Conv3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Conv3d'
    source_repr = 'Conv3d(4, 4, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1), groups=2)'
    source_configuration = (('', 'torch.nn.modules.conv', 'Conv3d', (('dilation', (1, 1, 1)), ('groups', 2), ('in_channels', 4), ('kernel_size', (3, 3, 3)), ('out_channels', 4), ('output_padding', (0, 0, 0)), ('padding', (1, 1, 1)), ('padding_mode', 'zeros'), ('stride', (2, 2, 2)), ('training', True), ('transposed', False))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((1, 4, 5, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    domain_node_25 = {'axes': (2, 3, 4), 'size': (3, 3, 3), 'stride': (2, 2, 2), 'dilation': (1, 1, 1), 'padding': ((1, 1), (1, 1), (1, 1)), 'output_axis': -1, 'kind': 'window'}

    def __init__(self, source):
        super().__init__(source)
        # constant_5: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_5', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_9: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_14: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_14', torch.tensor(
            [2, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_18: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_18', torch.tensor(
            [2, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class Conv3d(ExpandedModule):
    definition_type = Conv3dParameterDefinition

    def forward(self, x):
        # SCAN -> ((1, 4, 3, 3, 3), None)
        node_25 = d.LOOP.SCAN(
            self.node_25_body,
            x,
            None,
            domain=self.p.domain_node_25,
            parameters={'mode': 'shared', 'values': {'weight': self.p.param_weight, 'bias': self.p.param_bias}},
        )
        return node_25[0]

    def node_25_body(self, fragment, carry, parameters):
        # ROUTE -> (1, 2, 3, 3, 3)
        node_4 = d.route(fragment, self.p.constant_5, dim=1)
        # PERMUTE -> (1, 3, 3, 3, 2)
        node_6 = d.permute(node_4, (0, 2, 3, 4, 1))
        # RESHAPE -> (1, 54)
        node_7 = d.reshape(node_6, (1, -1))
        # ROUTE -> (2, 2, 3, 3, 3)
        node_8 = d.route(parameters['weight'], self.p.constant_9, dim=0)
        # PERMUTE -> (3, 3, 3, 2, 2)
        node_10 = d.permute(node_8, (2, 3, 4, 1, 0))
        # RESHAPE -> (54, 2)
        node_11 = d.reshape(node_10, (54, 2))
        # PROJECT -> (1, 2)
        node_12 = d.project(node_7, node_11)
        # ROUTE -> (1, 2, 3, 3, 3)
        node_13 = d.route(fragment, self.p.constant_14, dim=1)
        # PERMUTE -> (1, 3, 3, 3, 2)
        node_15 = d.permute(node_13, (0, 2, 3, 4, 1))
        # RESHAPE -> (1, 54)
        node_16 = d.reshape(node_15, (1, -1))
        # ROUTE -> (2, 2, 3, 3, 3)
        node_17 = d.route(parameters['weight'], self.p.constant_18, dim=0)
        # PERMUTE -> (3, 3, 3, 2, 2)
        node_19 = d.permute(node_17, (2, 3, 4, 1, 0))
        # RESHAPE -> (54, 2)
        node_20 = d.reshape(node_19, (54, 2))
        # PROJECT -> (1, 2)
        node_21 = d.project(node_16, node_20)
        # CONCAT -> (1, 4)
        node_22 = d.concat([node_12, node_21], dim=-1)
        # BROADCAST -> (1, 4)
        node_23 = d.broadcast(parameters['bias'], (1, 4))
        # ADD -> (1, 4)
        node_24 = d.add(node_22, node_23)
        return (node_24, None)
