"""ConvTranspose1d: expanded primitive implementation for ConvTranspose1d.

Configuration: groups=2, stride=2, padding=1, kernel=3; transposed output_padding=1; lazy materialized
Limitations: Only dense real kernels; padding_mode=zeros. No complex input, parametrization or lazy initialization semantics.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ConvTranspose1dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ConvTranspose1d'
    source_repr = 'ConvTranspose1d(4, 4, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,), groups=2)'
    source_configuration = (('', 'torch.nn.modules.conv', 'ConvTranspose1d', (('dilation', (1,)), ('groups', 2), ('in_channels', 4), ('kernel_size', (3,)), ('out_channels', 4), ('output_padding', (1,)), ('padding', (1,)), ('padding_mode', 'zeros'), ('stride', (2,)), ('training', True), ('transposed', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((1, 4, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_4: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_4', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_6: shape=(10, 3), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [[-1, 0, -1], [1, -1, 0], [-1, 1, -1], [2, -1, 1], [-1, 2, -1], [3, -1, 2], [-1, 3, -1],
             [4, -1, 3], [-1, 4, -1], [-1, -1, 4]],
            dtype=torch.int64, device='cpu').reshape((10, 3)))
        # constant_10: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_10', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_15: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [2, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_19: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_19', torch.tensor(
            [2, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class ConvTranspose1d(ExpandedModule):
    definition_type = ConvTranspose1dParameterDefinition

    def forward(self, x):
        # PERMUTE -> (1, 5, 4)
        node_1 = d.permute(x, (0, 2, 1))
        # RESHAPE -> (1, 5, 4)
        node_2 = d.reshape(node_1, (1, 5, 4))
        # ROUTE -> (1, 5, 2)
        node_3 = d.route(node_2, self.p.constant_4, dim=-1)
        # ROUTE -> (1, 10, 3, 2)
        node_5 = d.route(node_3, self.p.constant_6, padding='zero')
        # RESHAPE -> (1, 10, 6)
        node_7 = d.reshape(node_5, (1, 10, 6))
        # ROUTE -> (2, 2, 3)
        node_8 = d.route(self.p.param_weight, self.p.constant_10, dim=0)
        # PERMUTE -> (3, 2, 2)
        node_11 = d.permute(node_8, (2, 0, 1))
        # RESHAPE -> (6, 2)
        node_12 = d.reshape(node_11, (6, 2))
        # PROJECT -> (1, 10, 2)
        node_13 = d.project(node_7, node_12)
        # ROUTE -> (1, 5, 2)
        node_14 = d.route(node_2, self.p.constant_15, dim=-1)
        # ROUTE -> (1, 10, 3, 2)
        node_16 = d.route(node_14, self.p.constant_6, padding='zero')
        # RESHAPE -> (1, 10, 6)
        node_17 = d.reshape(node_16, (1, 10, 6))
        # ROUTE -> (2, 2, 3)
        node_18 = d.route(self.p.param_weight, self.p.constant_19, dim=0)
        # PERMUTE -> (3, 2, 2)
        node_20 = d.permute(node_18, (2, 0, 1))
        # RESHAPE -> (6, 2)
        node_21 = d.reshape(node_20, (6, 2))
        # PROJECT -> (1, 10, 2)
        node_22 = d.project(node_17, node_21)
        # CONCAT -> (1, 10, 4)
        node_23 = d.concat([node_13, node_22], dim=-1)
        # BROADCAST -> (1, 10, 4)
        node_24 = d.broadcast(self.p.param_bias, (1, 10, 4))
        # ADD -> (1, 10, 4)
        node_26 = d.add(node_23, node_24)
        # RESHAPE -> (1, 10, 4)
        node_27 = d.reshape(node_26, (1, 10, 4))
        # PERMUTE -> (1, 4, 10)
        node_28 = d.permute(node_27, (0, 2, 1))
        return node_28
