"""DataParallel: expanded primitive implementation for DataParallel.

Configuration: CPU single-device wrapper only
Limitations: No multi-device scatter/gather/communication tested.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class DataParallelParameterDefinition(ExpandedParameterDefinition):
    public_name = 'DataParallel'
    source_repr = 'DataParallel(\n  (module): Linear(in_features=3, out_features=2, bias=True)\n)'
    source_configuration = (('', 'torch.nn.parallel.data_parallel', 'DataParallel', (('device_ids', ()), ('training', True))), ('module', 'torch.nn.modules.linear', 'Linear', (('in_features', 3), ('out_features', 2), ('training', True))))
    frozen_buffers = {}
    source_modes = (('', True), ('module', True))
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')),)
    stateless = False

    @property
    def param_module_weight(self):
        return self.source.module.weight

    @property
    def param_module_bias(self):
        return self.source.module.bias


class DataParallel(ExpandedModule):
    definition_type = DataParallelParameterDefinition

    def forward(self, x):
        # PERMUTE -> (3, 2)
        node_1 = d.permute(self.p.param_module_weight, (1, 0))
        # PROJECT -> (2, 2)
        node_3 = d.project(x, node_1)
        # BROADCAST -> (2, 2)
        node_4 = d.broadcast(self.p.param_module_bias, (2, 2))
        # ADD -> (2, 2)
        node_6 = d.add(node_3, node_4)
        return node_6
