"""Dropout3d: expanded primitive implementation for Dropout3d.

Configuration: eval() only, p=.3
Limitations: Eval identity does not express training-time RNG or random mask sampling.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class Dropout3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Dropout3d'
    source_repr = 'Dropout3d(p=0.3, inplace=False)'
    source_configuration = (('', 'torch.nn.modules.dropout', 'Dropout3d', (('inplace', False), ('p', 0.3), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 2, 2, 2, 2), torch.float64, torch.device('cpu')),)
    stateless = False


class Dropout3d(ExpandedModule):
    definition_type = Dropout3dParameterDefinition

    def forward(self, x):
        # NONLINEAR -> (2, 2, 2, 2, 2)
        node_1 = d.nonlinear(x, activation='identity')
        return node_1
