"""EmbeddingBag: expanded primitive implementation for EmbeddingBag.

Configuration: dense gradients; 2D indices; no padding_idx/max_norm/frequency scaling/sparse gradients
Limitations: EmbeddingBag fixed equal-length bags only; parameter gradient checked, indices non-differentiable.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class EmbeddingBagParameterDefinition(ExpandedParameterDefinition):
    public_name = 'EmbeddingBag'
    source_repr = "EmbeddingBag(7, 3, mode='mean')"
    source_configuration = (('', 'torch.nn.modules.sparse', 'EmbeddingBag', (('embedding_dim', 3), ('include_last_offset', False), ('max_norm', None), ('mode', 'mean'), ('norm_type', 2.0), ('num_embeddings', 7), ('padding_idx', None), ('scale_grad_by_freq', False), ('sparse', False), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.int64, torch.device('cpu')),)
    stateless = False

    @property
    def param_weight(self):
        return self.source.weight


class EmbeddingBag(ExpandedModule):
    definition_type = EmbeddingBagParameterDefinition

    def forward(self, x):
        # ROUTE -> (2, 3, 3)
        node_1 = d.route(self.p.param_weight, x, dim=0)
        # AGGREGATE -> (2, 3)
        node_3 = d.aggregate(node_1, reducer='mean')
        return node_3
