"""Embedding: expanded primitive implementation for Embedding.

Configuration: dense gradients; 2D indices; no padding_idx/max_norm/frequency scaling/sparse gradients
Limitations: EmbeddingBag fixed equal-length bags only; parameter gradient checked, indices non-differentiable.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class EmbeddingParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Embedding'
    source_repr = 'Embedding(7, 3)'
    source_configuration = (('', 'torch.nn.modules.sparse', 'Embedding', (('embedding_dim', 3), ('max_norm', None), ('norm_type', 2.0), ('num_embeddings', 7), ('padding_idx', None), ('scale_grad_by_freq', False), ('sparse', False), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.int64, torch.device('cpu')),)
    stateless = False

    @property
    def param_weight(self):
        return self.source.weight


class Embedding(ExpandedModule):
    definition_type = EmbeddingParameterDefinition

    def forward(self, x):
        # ROUTE -> (2, 3, 3)
        node_1 = d.route(self.p.param_weight, x, dim=0)
        return node_1
