"""Flatten: expanded primitive implementation for Flatten.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class FlattenParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Flatten'
    source_repr = 'Flatten(start_dim=1, end_dim=-1)'
    source_configuration = (('', 'torch.nn.modules.flatten', 'Flatten', (('end_dim', -1), ('start_dim', 1), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False


class Flatten(ExpandedModule):
    definition_type = FlattenParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 12)
        node_1 = d.reshape(x, (2, 12))
        return node_1
