"""GLU: expanded primitive implementation for GLU.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class GLUParameterDefinition(ExpandedParameterDefinition):
    public_name = 'GLU'
    source_repr = 'GLU(dim=-1)'
    source_configuration = (('', 'torch.nn.modules.activation', 'GLU', (('dim', -1), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_2: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_2', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_4: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_4', torch.tensor(
            [2, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))


class GLU(ExpandedModule):
    definition_type = GLUParameterDefinition

    def forward(self, x):
        # ROUTE -> (2, 3, 2)
        node_1 = d.route(x, self.p.constant_2, dim=-1)
        # ROUTE -> (2, 3, 2)
        node_3 = d.route(x, self.p.constant_4, dim=-1)
        # GATE -> (2, 3, 2)
        node_5 = d.gate(node_3, node_1)
        return node_5
