"""GroupNorm: expanded primitive implementation for GroupNorm.

Configuration: 2 groups; affine=True
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class GroupNormParameterDefinition(ExpandedParameterDefinition):
    public_name = 'GroupNorm'
    source_repr = 'GroupNorm(2, 4, eps=1e-05, affine=True, bias=True)'
    source_configuration = (('', 'torch.nn.modules.normalization', 'GroupNorm', (('affine', True), ('eps', 1e-05), ('num_channels', 4), ('num_groups', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 4, 3, 3), torch.float64, torch.device('cpu')),)
    stateless = False

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class GroupNorm(ExpandedModule):
    definition_type = GroupNormParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 2, 18)
        node_1 = d.reshape(x, (2, 2, -1))
        # NORM -> (2, 2, 18)
        node_2 = d.norm(node_1, eps=1e-05)
        # RESHAPE -> (2, 4, 3, 3)
        node_3 = d.reshape(node_2, (2, 4, 3, 3))
        # RESHAPE -> (1, 4, 1, 1)
        node_4 = d.reshape(self.p.param_weight, (1, 4, 1, 1))
        # BROADCAST -> (2, 4, 3, 3)
        node_6 = d.broadcast(node_4, (2, 4, 3, 3))
        # MUL -> (2, 4, 3, 3)
        node_7 = d.mul(node_3, node_6)
        # RESHAPE -> (1, 4, 1, 1)
        node_8 = d.reshape(self.p.param_bias, (1, 4, 1, 1))
        # BROADCAST -> (2, 4, 3, 3)
        node_10 = d.broadcast(node_8, (2, 4, 3, 3))
        # ADD -> (2, 4, 3, 3)
        node_11 = d.add(node_7, node_10)
        return node_11
