"""GRU: expanded primitive implementation for GRU.

Configuration: one layer, one direction, T=3, no dropout or packed sequence
Limitations: PackedSequence, projected LSTM, multi-layer/bidirectional combinations not included.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class GRUParameterDefinition(ExpandedParameterDefinition):
    public_name = 'GRU'
    source_repr = 'GRU(3, 4)'
    source_configuration = (('', 'torch.nn.modules.rnn', 'GRU', (('batch_first', False), ('bias', True), ('bidirectional', False), ('dropout', 0.0), ('hidden_size', 4), ('input_size', 3), ('mode', 'GRU'), ('num_layers', 1), ('proj_size', 0), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((3, 2, 3), torch.float64, torch.device('cpu')), TensorSpec((1, 2, 4), torch.float64, torch.device('cpu')))
    stateless = False

    domain_node_47 = {'axis': 0, 'out_dim': 0, 'reverse': False, 'kind': 'sequence'}

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(1,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0],
            dtype=torch.int64, device='cpu').reshape((1,)))
        # constant_20: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_20', torch.tensor(
            [0, 1, 2, 3],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_22: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_22', torch.tensor(
            [4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_24: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_24', torch.tensor(
            [8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_26: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_26', torch.tensor(
            [0, 1, 2, 3],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_28: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_28', torch.tensor(
            [4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_30: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_30', torch.tensor(
            [8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_39: shape=(), dtype=torch.float64
        self.register_buffer('constant_39', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_41: shape=(), dtype=torch.float64
        self.register_buffer('constant_41', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))

    @property
    def param_weight_ih_l0(self):
        return self.source.weight_ih_l0

    @property
    def param_bias_ih_l0(self):
        return self.source.bias_ih_l0

    @property
    def param_weight_hh_l0(self):
        return self.source.weight_hh_l0

    @property
    def param_bias_hh_l0(self):
        return self.source.bias_hh_l0


class GRU(ExpandedModule):
    definition_type = GRUParameterDefinition

    def forward(self, x, state):
        # ROUTE -> (1, 2, 4)
        node_2 = d.route(state, self.p.constant_3, dim=0)
        # RESHAPE -> (2, 4)
        node_4 = d.reshape(node_2, [2, 4])
        # SCAN -> ((3, 2, 4), (2, 4))
        node_47 = d.LOOP.SCAN(
            self.node_47_body,
            x,
            node_4,
            domain=self.p.domain_node_47,
            parameters=None,
        )
        # RESHAPE -> (1, 2, 4)
        node_48 = d.reshape(node_47[1], (1, 2, 4))
        return (node_47[0], node_48)

    def node_47_body(self, fragment, carry, parameters):
        # PERMUTE -> (3, 12)
        node_7 = d.permute(self.p.param_weight_ih_l0, (1, 0))
        # PROJECT -> (2, 12)
        node_9 = d.project(fragment, node_7)
        # BROADCAST -> (2, 12)
        node_10 = d.broadcast(self.p.param_bias_ih_l0, (2, 12))
        # ADD -> (2, 12)
        node_12 = d.add(node_9, node_10)
        # PERMUTE -> (4, 12)
        node_13 = d.permute(self.p.param_weight_hh_l0, (1, 0))
        # PROJECT -> (2, 12)
        node_15 = d.project(carry, node_13)
        # BROADCAST -> (2, 12)
        node_16 = d.broadcast(self.p.param_bias_hh_l0, (2, 12))
        # ADD -> (2, 12)
        node_18 = d.add(node_15, node_16)
        # ROUTE -> (2, 4)
        node_19 = d.route(node_12, self.p.constant_20, dim=-1)
        # ROUTE -> (2, 4)
        node_21 = d.route(node_12, self.p.constant_22, dim=-1)
        # ROUTE -> (2, 4)
        node_23 = d.route(node_12, self.p.constant_24, dim=-1)
        # ROUTE -> (2, 4)
        node_25 = d.route(node_18, self.p.constant_26, dim=-1)
        # ROUTE -> (2, 4)
        node_27 = d.route(node_18, self.p.constant_28, dim=-1)
        # ROUTE -> (2, 4)
        node_29 = d.route(node_18, self.p.constant_30, dim=-1)
        # ADD -> (2, 4)
        node_31 = d.add(node_19, node_25)
        # NONLINEAR -> (2, 4)
        node_32 = d.nonlinear(node_31, activation='sigmoid')
        # ADD -> (2, 4)
        node_33 = d.add(node_21, node_27)
        # NONLINEAR -> (2, 4)
        node_34 = d.nonlinear(node_33, activation='sigmoid')
        # MUL -> (2, 4)
        node_35 = d.mul(node_32, node_29)
        # ADD -> (2, 4)
        node_36 = d.add(node_23, node_35)
        # NONLINEAR -> (2, 4)
        node_37 = d.nonlinear(node_36, activation='tanh')
        # BROADCAST -> (2, 4)
        node_38 = d.broadcast(self.p.constant_39, (2, 4))
        # BROADCAST -> (2, 4)
        node_40 = d.broadcast(self.p.constant_41, (2, 4))
        # MUL -> (2, 4)
        node_42 = d.mul(node_34, node_40)
        # ADD -> (2, 4)
        node_43 = d.add(node_38, node_42)
        # MUL -> (2, 4)
        node_44 = d.mul(node_43, node_37)
        # MUL -> (2, 4)
        node_45 = d.mul(node_34, carry)
        # ADD -> (2, 4)
        node_46 = d.add(node_44, node_45)
        return (node_46, node_46)
