"""GRUCell: expanded primitive implementation for GRUCell.

Configuration: single step; nonzero state; bias=True
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class GRUCellParameterDefinition(ExpandedParameterDefinition):
    public_name = 'GRUCell'
    source_repr = 'GRUCell(3, 4)'
    source_configuration = (('', 'torch.nn.modules.rnn', 'GRUCell', (('bias', True), ('hidden_size', 4), ('input_size', 3), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 4), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_15: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [0, 1, 2, 3],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_17: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_17', torch.tensor(
            [4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_19: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_19', torch.tensor(
            [8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_21: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [0, 1, 2, 3],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_23: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_23', torch.tensor(
            [4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_25: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_25', torch.tensor(
            [8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_34: shape=(), dtype=torch.float64
        self.register_buffer('constant_34', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_36: shape=(), dtype=torch.float64
        self.register_buffer('constant_36', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))

    @property
    def param_weight_ih(self):
        return self.source.weight_ih

    @property
    def param_bias_ih(self):
        return self.source.bias_ih

    @property
    def param_weight_hh(self):
        return self.source.weight_hh

    @property
    def param_bias_hh(self):
        return self.source.bias_hh


class GRUCell(ExpandedModule):
    definition_type = GRUCellParameterDefinition

    def forward(self, x, state):
        # PERMUTE -> (3, 12)
        node_2 = d.permute(self.p.param_weight_ih, (1, 0))
        # PROJECT -> (2, 12)
        node_4 = d.project(x, node_2)
        # BROADCAST -> (2, 12)
        node_5 = d.broadcast(self.p.param_bias_ih, (2, 12))
        # ADD -> (2, 12)
        node_7 = d.add(node_4, node_5)
        # PERMUTE -> (4, 12)
        node_8 = d.permute(self.p.param_weight_hh, (1, 0))
        # PROJECT -> (2, 12)
        node_10 = d.project(state, node_8)
        # BROADCAST -> (2, 12)
        node_11 = d.broadcast(self.p.param_bias_hh, (2, 12))
        # ADD -> (2, 12)
        node_13 = d.add(node_10, node_11)
        # ROUTE -> (2, 4)
        node_14 = d.route(node_7, self.p.constant_15, dim=-1)
        # ROUTE -> (2, 4)
        node_16 = d.route(node_7, self.p.constant_17, dim=-1)
        # ROUTE -> (2, 4)
        node_18 = d.route(node_7, self.p.constant_19, dim=-1)
        # ROUTE -> (2, 4)
        node_20 = d.route(node_13, self.p.constant_21, dim=-1)
        # ROUTE -> (2, 4)
        node_22 = d.route(node_13, self.p.constant_23, dim=-1)
        # ROUTE -> (2, 4)
        node_24 = d.route(node_13, self.p.constant_25, dim=-1)
        # ADD -> (2, 4)
        node_26 = d.add(node_14, node_20)
        # NONLINEAR -> (2, 4)
        node_27 = d.nonlinear(node_26, activation='sigmoid')
        # ADD -> (2, 4)
        node_28 = d.add(node_16, node_22)
        # NONLINEAR -> (2, 4)
        node_29 = d.nonlinear(node_28, activation='sigmoid')
        # MUL -> (2, 4)
        node_30 = d.mul(node_27, node_24)
        # ADD -> (2, 4)
        node_31 = d.add(node_18, node_30)
        # NONLINEAR -> (2, 4)
        node_32 = d.nonlinear(node_31, activation='tanh')
        # BROADCAST -> (2, 4)
        node_33 = d.broadcast(self.p.constant_34, (2, 4))
        # BROADCAST -> (2, 4)
        node_35 = d.broadcast(self.p.constant_36, (2, 4))
        # MUL -> (2, 4)
        node_37 = d.mul(node_29, node_35)
        # ADD -> (2, 4)
        node_38 = d.add(node_33, node_37)
        # MUL -> (2, 4)
        node_39 = d.mul(node_38, node_32)
        # MUL -> (2, 4)
        node_40 = d.mul(node_29, state)
        # ADD -> (2, 4)
        node_41 = d.add(node_39, node_40)
        return node_41
