"""Hardtanh: expanded primitive implementation for Hardtanh.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class HardtanhParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Hardtanh'
    source_repr = 'Hardtanh(min_val=-1.0, max_val=1.0)'
    source_configuration = (('', 'torch.nn.modules.activation', 'Hardtanh', (('inplace', False), ('max_val', 1.0), ('min_val', -1.0), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_2: shape=(), dtype=torch.float64
        self.register_buffer('constant_2', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_4: shape=(), dtype=torch.float64
        self.register_buffer('constant_4', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_6: shape=(), dtype=torch.float64
        self.register_buffer('constant_6', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_11: shape=(), dtype=torch.float64
        self.register_buffer('constant_11', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_13: shape=(), dtype=torch.float64
        self.register_buffer('constant_13', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_18: shape=(), dtype=torch.float64
        self.register_buffer('constant_18', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class Hardtanh(ExpandedModule):
    definition_type = HardtanhParameterDefinition

    def forward(self, x):
        # BROADCAST -> (2, 3, 4)
        node_1 = d.broadcast(self.p.constant_2, (2, 3, 4))
        # BROADCAST -> (2, 3, 4)
        node_3 = d.broadcast(self.p.constant_4, (2, 3, 4))
        # BROADCAST -> (2, 3, 4)
        node_5 = d.broadcast(self.p.constant_6, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_7 = d.mul(node_3, node_5)
        # ADD -> (2, 3, 4)
        node_8 = d.add(x, node_7)
        # NONLINEAR -> (2, 3, 4)
        node_9 = d.nonlinear(node_8)
        # BROADCAST -> (2, 3, 4)
        node_10 = d.broadcast(self.p.constant_11, (2, 3, 4))
        # BROADCAST -> (2, 3, 4)
        node_12 = d.broadcast(self.p.constant_13, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_14 = d.mul(node_10, node_12)
        # ADD -> (2, 3, 4)
        node_15 = d.add(x, node_14)
        # NONLINEAR -> (2, 3, 4)
        node_16 = d.nonlinear(node_15)
        # BROADCAST -> (2, 3, 4)
        node_17 = d.broadcast(self.p.constant_18, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_19 = d.mul(node_16, node_17)
        # ADD -> (2, 3, 4)
        node_20 = d.add(node_9, node_19)
        # ADD -> (2, 3, 4)
        node_21 = d.add(node_1, node_20)
        return node_21
