"""HingeEmbeddingLoss: expanded primitive implementation for HingeEmbeddingLoss.

Configuration: default reductions, valid labels; no class weights/ignore_index
Limitations: Index-selection lowering can create quadratic intermediates; no sparse-gradient or ignored-label contract.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class HingeEmbeddingLossParameterDefinition(ExpandedParameterDefinition):
    public_name = 'HingeEmbeddingLoss'
    source_repr = 'HingeEmbeddingLoss()'
    source_configuration = (('', 'torch.nn.modules.loss', 'HingeEmbeddingLoss', (('margin', 1.0), ('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 3), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_6: shape=(), dtype=torch.float64
        self.register_buffer('constant_6', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(), dtype=torch.float64
        self.register_buffer('constant_9', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_11: shape=(), dtype=torch.float64
        self.register_buffer('constant_11', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_16: shape=(), dtype=torch.float64
        self.register_buffer('constant_16', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_18: shape=(), dtype=torch.float64
        self.register_buffer('constant_18', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class HingeEmbeddingLoss(ExpandedModule):
    definition_type = HingeEmbeddingLossParameterDefinition

    def forward(self, x, target):
        # BROADCAST -> (2, 3)
        node_2 = d.broadcast(self.p.constant_3, (2, 3))
        # ADD -> (2, 3)
        node_4 = d.add(target, node_2)
        # BROADCAST -> (2, 3)
        node_5 = d.broadcast(self.p.constant_6, (2, 3))
        # MUL -> (2, 3)
        node_7 = d.mul(node_4, node_5)
        # BROADCAST -> (2, 3)
        node_8 = d.broadcast(self.p.constant_9, (2, 3))
        # BROADCAST -> (2, 3)
        node_10 = d.broadcast(self.p.constant_11, (2, 3))
        # MUL -> (2, 3)
        node_12 = d.mul(node_7, node_10)
        # ADD -> (2, 3)
        node_13 = d.add(node_8, node_12)
        # MUL -> (2, 3)
        node_14 = d.mul(node_7, x)
        # BROADCAST -> (2, 3)
        node_15 = d.broadcast(self.p.constant_16, (2, 3))
        # BROADCAST -> (2, 3)
        node_17 = d.broadcast(self.p.constant_18, (2, 3))
        # MUL -> (2, 3)
        node_19 = d.mul(x, node_17)
        # ADD -> (2, 3)
        node_20 = d.add(node_15, node_19)
        # NONLINEAR -> (2, 3)
        node_21 = d.nonlinear(node_20)
        # MUL -> (2, 3)
        node_22 = d.mul(node_13, node_21)
        # ADD -> (2, 3)
        node_23 = d.add(node_14, node_22)
        # REDUCE -> ()
        node_24 = d.reduce(node_23, dim=(0, 1), reducer='mean')
        return node_24
