"""HuberLoss: expanded primitive implementation for HuberLoss.

Configuration: default mean reduction
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class HuberLossParameterDefinition(ExpandedParameterDefinition):
    public_name = 'HuberLoss'
    source_repr = 'HuberLoss()'
    source_configuration = (('', 'torch.nn.modules.loss', 'HuberLoss', (('delta', 1.0), ('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 3), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_8: shape=(), dtype=torch.float64
        self.register_buffer('constant_8', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_13: shape=(), dtype=torch.float64
        self.register_buffer('constant_13', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_15: shape=(), dtype=torch.float64
        self.register_buffer('constant_15', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_22: shape=(), dtype=torch.float64
        self.register_buffer('constant_22', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_26: shape=(), dtype=torch.float64
        self.register_buffer('constant_26', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))


class HuberLoss(ExpandedModule):
    definition_type = HuberLossParameterDefinition

    def forward(self, x, target):
        # BROADCAST -> (2, 3)
        node_2 = d.broadcast(self.p.constant_3, (2, 3))
        # MUL -> (2, 3)
        node_4 = d.mul(target, node_2)
        # ADD -> (2, 3)
        node_5 = d.add(x, node_4)
        # NONLINEAR -> (2, 3)
        node_6 = d.nonlinear(node_5)
        # BROADCAST -> (2, 3)
        node_7 = d.broadcast(self.p.constant_8, (2, 3))
        # MUL -> (2, 3)
        node_9 = d.mul(node_5, node_7)
        # NONLINEAR -> (2, 3)
        node_10 = d.nonlinear(node_9)
        # ADD -> (2, 3)
        node_11 = d.add(node_6, node_10)
        # BROADCAST -> (2, 3)
        node_12 = d.broadcast(self.p.constant_13, (2, 3))
        # BROADCAST -> (2, 3)
        node_14 = d.broadcast(self.p.constant_15, (2, 3))
        # MUL -> (2, 3)
        node_16 = d.mul(node_12, node_14)
        # ADD -> (2, 3)
        node_17 = d.add(node_11, node_16)
        # NONLINEAR -> (2, 3)
        node_18 = d.nonlinear(node_17)
        # MUL -> (2, 3)
        node_19 = d.mul(node_11, node_11)
        # MUL -> (2, 3)
        node_20 = d.mul(node_18, node_18)
        # BROADCAST -> (2, 3)
        node_21 = d.broadcast(self.p.constant_22, (2, 3))
        # MUL -> (2, 3)
        node_23 = d.mul(node_20, node_21)
        # ADD -> (2, 3)
        node_24 = d.add(node_19, node_23)
        # BROADCAST -> (2, 3)
        node_25 = d.broadcast(self.p.constant_26, (2, 3))
        # MUL -> (2, 3)
        node_27 = d.mul(node_24, node_25)
        # REDUCE -> ()
        node_28 = d.reduce(node_27, dim=(0, 1), reducer='mean')
        return node_28
