"""InstanceNorm3d: expanded primitive implementation for InstanceNorm3d.

Configuration: eval(); fixed running buffers; affine=True; lazy materialized
Limitations: Only inference, no running-stat updates or distributed all-reduce. Train-mode outputs are tested separately.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class InstanceNorm3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'InstanceNorm3d'
    source_repr = 'InstanceNorm3d(4, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)'
    source_configuration = (('', 'torch.nn.modules.instancenorm', 'InstanceNorm3d', (('affine', True), ('eps', 1e-05), ('momentum', 0.1), ('num_features', 4), ('track_running_stats', True), ('training', False))),)
    frozen_buffers = {'running_mean': [0.0, 0.0, 0.0, 0.0], 'running_var': [1.0, 1.0, 1.0, 1.0], 'num_batches_tracked': 0}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 4, 3, 3, 3), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_5: shape=(), dtype=torch.float64
        self.register_buffer('constant_5', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(4,), dtype=torch.float64
        self.register_buffer('constant_9', torch.tensor(
            [0.9999950000374997, 0.9999950000374997, 0.9999950000374997, 0.9999950000374997],
            dtype=torch.float64, device='cpu').reshape((4,)))

    @property
    def param_running_mean(self):
        return self.source.running_mean

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class InstanceNorm3d(ExpandedModule):
    definition_type = InstanceNorm3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_1 = d.reshape(self.p.param_running_mean, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_3 = d.broadcast(node_1, (2, 4, 3, 3, 3))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_4 = d.broadcast(self.p.constant_5, (2, 4, 3, 3, 3))
        # MUL -> (2, 4, 3, 3, 3)
        node_6 = d.mul(node_3, node_4)
        # ADD -> (2, 4, 3, 3, 3)
        node_7 = d.add(x, node_6)
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_8 = d.reshape(self.p.constant_9, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_10 = d.broadcast(node_8, (2, 4, 3, 3, 3))
        # MUL -> (2, 4, 3, 3, 3)
        node_11 = d.mul(node_7, node_10)
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_12 = d.reshape(self.p.param_weight, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_14 = d.broadcast(node_12, (2, 4, 3, 3, 3))
        # MUL -> (2, 4, 3, 3, 3)
        node_15 = d.mul(node_11, node_14)
        # RESHAPE -> (1, 4, 1, 1, 1)
        node_16 = d.reshape(self.p.param_bias, (1, 4, 1, 1, 1))
        # BROADCAST -> (2, 4, 3, 3, 3)
        node_18 = d.broadcast(node_16, (2, 4, 3, 3, 3))
        # ADD -> (2, 4, 3, 3, 3)
        node_19 = d.add(node_15, node_18)
        return node_19
