"""L1Loss: expanded primitive implementation for L1Loss.

Configuration: default mean reduction
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class L1LossParameterDefinition(ExpandedParameterDefinition):
    public_name = 'L1Loss'
    source_repr = 'L1Loss()'
    source_configuration = (('', 'torch.nn.modules.loss', 'L1Loss', (('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 3), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_8: shape=(), dtype=torch.float64
        self.register_buffer('constant_8', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class L1Loss(ExpandedModule):
    definition_type = L1LossParameterDefinition

    def forward(self, x, target):
        # BROADCAST -> (2, 3)
        node_2 = d.broadcast(self.p.constant_3, (2, 3))
        # MUL -> (2, 3)
        node_4 = d.mul(target, node_2)
        # ADD -> (2, 3)
        node_5 = d.add(x, node_4)
        # NONLINEAR -> (2, 3)
        node_6 = d.nonlinear(node_5)
        # BROADCAST -> (2, 3)
        node_7 = d.broadcast(self.p.constant_8, (2, 3))
        # MUL -> (2, 3)
        node_9 = d.mul(node_5, node_7)
        # NONLINEAR -> (2, 3)
        node_10 = d.nonlinear(node_9)
        # ADD -> (2, 3)
        node_11 = d.add(node_6, node_10)
        # REDUCE -> ()
        node_12 = d.reduce(node_11, dim=(0, 1), reducer='mean')
        return node_12
