"""LayerNorm: expanded primitive implementation for LayerNorm.

Configuration: two trailing normalized axes; eps=1e-5
Limitations: RMSNorm lowered using NORM([x,-x]) then selecting the first half; no new primitive.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class LayerNormParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LayerNorm'
    source_repr = 'LayerNorm((3, 4), eps=1e-05, elementwise_affine=True, bias=True)'
    source_configuration = (('', 'torch.nn.modules.normalization', 'LayerNorm', (('elementwise_affine', True), ('eps', 1e-05), ('normalized_shape', (3, 4)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class LayerNorm(ExpandedModule):
    definition_type = LayerNormParameterDefinition

    def forward(self, x):
        # NORM -> (2, 3, 4)
        node_1 = d.norm(x, normalized_shape=(3, 4), weight=self.p.param_weight, bias=self.p.param_bias, eps=1e-05)
        return node_1
