"""LazyLinear: expanded primitive implementation for LazyLinear.

Configuration: bias=True; lazy tested after materialization
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class LazyLinearParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LazyLinear'
    source_repr = 'Linear(in_features=3, out_features=4, bias=True)'
    source_configuration = (('', 'torch.nn.modules.linear', 'Linear', (('in_features', 3), ('out_features', 4), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 5, 3), torch.float64, torch.device('cpu')),)
    stateless = False

    @property
    def param_weight(self):
        return self.source.weight

    @property
    def param_bias(self):
        return self.source.bias


class LazyLinear(ExpandedModule):
    definition_type = LazyLinearParameterDefinition

    def forward(self, x):
        # PERMUTE -> (3, 4)
        node_1 = d.permute(self.p.param_weight, (1, 0))
        # PROJECT -> (2, 5, 4)
        node_3 = d.project(x, node_1)
        # BROADCAST -> (2, 5, 4)
        node_4 = d.broadcast(self.p.param_bias, (2, 5, 4))
        # ADD -> (2, 5, 4)
        node_6 = d.add(node_3, node_4)
        return node_6
