"""LPPool1d: expanded primitive implementation for LPPool1d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: LPPool p=1 only; arbitrary p requires power/root support.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class LPPool1dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LPPool1d'
    source_repr = 'LPPool1d(norm_type=1, kernel_size=2, stride=2, ceil_mode=False)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'LPPool1d', (('ceil_mode', False), ('kernel_size', 2), ('norm_type', 1), ('stride', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_6: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [2, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))


class LPPool1d(ExpandedModule):
    definition_type = LPPool1dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 5)
        node_1 = d.reshape(x, (2, 3, 5))
        # ROUTE -> (2, 3, 2)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 2)
        node_5 = d.route(node_1, self.p.constant_6, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_7 = d.reduce(node_5, dim=-1, reducer='sum', keepdim=True)
        # CONCAT -> (2, 3, 2)
        node_8 = d.concat([node_4, node_7], dim=-1)
        # RESHAPE -> (2, 3, 2)
        node_9 = d.reshape(node_8, (2, 3, 2))
        return node_9
