"""LPPool3d: expanded primitive implementation for LPPool3d.

Configuration: small dense input; no ceil_mode; output_size=2 or kernel=2/stride=2
Limitations: LPPool p=1 only; arbitrary p requires power/root support.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class LPPool3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LPPool3d'
    source_repr = 'LPPool3d(norm_type=1, kernel_size=2, stride=2, ceil_mode=False)'
    source_configuration = (('', 'torch.nn.modules.pooling', 'LPPool3d', (('ceil_mode', False), ('kernel_size', 2), ('norm_type', 1), ('stride', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 5, 5, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 5, 6, 25, 26, 30, 31],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_6: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [2, 3, 7, 8, 27, 28, 32, 33],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_9: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [10, 11, 15, 16, 35, 36, 40, 41],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_12: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_12', torch.tensor(
            [12, 13, 17, 18, 37, 38, 42, 43],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_15: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_15', torch.tensor(
            [50, 51, 55, 56, 75, 76, 80, 81],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_18: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_18', torch.tensor(
            [52, 53, 57, 58, 77, 78, 82, 83],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_21: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [60, 61, 65, 66, 85, 86, 90, 91],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_24: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_24', torch.tensor(
            [62, 63, 67, 68, 87, 88, 92, 93],
            dtype=torch.int64, device='cpu').reshape((8,)))


class LPPool3d(ExpandedModule):
    definition_type = LPPool3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 125)
        node_1 = d.reshape(x, (2, 3, 125))
        # ROUTE -> (2, 3, 8)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_4 = d.reduce(node_2, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_5 = d.route(node_1, self.p.constant_6, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_7 = d.reduce(node_5, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_8 = d.route(node_1, self.p.constant_9, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_10 = d.reduce(node_8, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_11 = d.route(node_1, self.p.constant_12, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_13 = d.reduce(node_11, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_14 = d.route(node_1, self.p.constant_15, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_16 = d.reduce(node_14, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_17 = d.route(node_1, self.p.constant_18, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_19 = d.reduce(node_17, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_20 = d.route(node_1, self.p.constant_21, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_22 = d.reduce(node_20, dim=-1, reducer='sum', keepdim=True)
        # ROUTE -> (2, 3, 8)
        node_23 = d.route(node_1, self.p.constant_24, dim=-1, padding='zero')
        # REDUCE -> (2, 3, 1)
        node_25 = d.reduce(node_23, dim=-1, reducer='sum', keepdim=True)
        # CONCAT -> (2, 3, 8)
        node_26 = d.concat([node_4, node_7, node_10, node_13, node_16, node_19, node_22, node_25], dim=-1)
        # RESHAPE -> (2, 3, 2, 2, 2)
        node_27 = d.reshape(node_26, (2, 3, 2, 2, 2))
        return node_27
