"""LSTMCell: expanded primitive implementation for LSTMCell.

Configuration: single step; nonzero state; bias=True
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class LSTMCellParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LSTMCell'
    source_repr = 'LSTMCell(3, 4)'
    source_configuration = (('', 'torch.nn.modules.rnn', 'LSTMCell', (('bias', True), ('hidden_size', 4), ('input_size', 3), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), (TensorSpec((2, 4), torch.float64, torch.device('cpu')), TensorSpec((2, 4), torch.float64, torch.device('cpu'))))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_17: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_17', torch.tensor(
            [0, 1, 2, 3],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_19: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_19', torch.tensor(
            [4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_21: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_21', torch.tensor(
            [8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_23: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_23', torch.tensor(
            [12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((4,)))

    @property
    def param_weight_ih(self):
        return self.source.weight_ih

    @property
    def param_bias_ih(self):
        return self.source.bias_ih

    @property
    def param_weight_hh(self):
        return self.source.weight_hh

    @property
    def param_bias_hh(self):
        return self.source.bias_hh


class LSTMCell(ExpandedModule):
    definition_type = LSTMCellParameterDefinition

    def forward(self, x, state):
        # PERMUTE -> (3, 16)
        node_3 = d.permute(self.p.param_weight_ih, (1, 0))
        # PROJECT -> (2, 16)
        node_5 = d.project(x, node_3)
        # BROADCAST -> (2, 16)
        node_6 = d.broadcast(self.p.param_bias_ih, (2, 16))
        # ADD -> (2, 16)
        node_8 = d.add(node_5, node_6)
        # PERMUTE -> (4, 16)
        node_9 = d.permute(self.p.param_weight_hh, (1, 0))
        # PROJECT -> (2, 16)
        node_11 = d.project(state[0], node_9)
        # BROADCAST -> (2, 16)
        node_12 = d.broadcast(self.p.param_bias_hh, (2, 16))
        # ADD -> (2, 16)
        node_14 = d.add(node_11, node_12)
        # ADD -> (2, 16)
        node_15 = d.add(node_8, node_14)
        # ROUTE -> (2, 4)
        node_16 = d.route(node_15, self.p.constant_17, dim=-1)
        # ROUTE -> (2, 4)
        node_18 = d.route(node_15, self.p.constant_19, dim=-1)
        # ROUTE -> (2, 4)
        node_20 = d.route(node_15, self.p.constant_21, dim=-1)
        # ROUTE -> (2, 4)
        node_22 = d.route(node_15, self.p.constant_23, dim=-1)
        # NONLINEAR -> (2, 4)
        node_24 = d.nonlinear(node_16, activation='sigmoid')
        # NONLINEAR -> (2, 4)
        node_25 = d.nonlinear(node_18, activation='sigmoid')
        # NONLINEAR -> (2, 4)
        node_26 = d.nonlinear(node_20, activation='tanh')
        # NONLINEAR -> (2, 4)
        node_27 = d.nonlinear(node_22, activation='sigmoid')
        # MUL -> (2, 4)
        node_28 = d.mul(node_25, state[1])
        # MUL -> (2, 4)
        node_29 = d.mul(node_24, node_26)
        # ADD -> (2, 4)
        node_30 = d.add(node_28, node_29)
        # NONLINEAR -> (2, 4)
        node_31 = d.nonlinear(node_30, activation='tanh')
        # MUL -> (2, 4)
        node_32 = d.mul(node_27, node_31)
        return (node_32, node_30)
