"""LSTM: expanded primitive implementation for LSTM.

Configuration: one layer, one direction, T=3, no dropout or packed sequence
Limitations: PackedSequence, projected LSTM, multi-layer/bidirectional combinations not included.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class LSTMParameterDefinition(ExpandedParameterDefinition):
    public_name = 'LSTM'
    source_repr = 'LSTM(3, 4)'
    source_configuration = (('', 'torch.nn.modules.rnn', 'LSTM', (('batch_first', False), ('bias', True), ('bidirectional', False), ('dropout', 0.0), ('hidden_size', 4), ('input_size', 3), ('mode', 'LSTM'), ('num_layers', 1), ('proj_size', 0), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((3, 2, 3), torch.float64, torch.device('cpu')), (TensorSpec((1, 2, 4), torch.float64, torch.device('cpu')), TensorSpec((1, 2, 4), torch.float64, torch.device('cpu'))))
    stateless = False

    domain_node_42 = {'axis': 0, 'out_dim': 0, 'reverse': False, 'kind': 'sequence'}

    def __init__(self, source):
        super().__init__(source)
        # constant_4: shape=(1,), dtype=torch.int64
        self.register_buffer('constant_4', torch.tensor(
            [0],
            dtype=torch.int64, device='cpu').reshape((1,)))
        # constant_7: shape=(1,), dtype=torch.int64
        self.register_buffer('constant_7', torch.tensor(
            [0],
            dtype=torch.int64, device='cpu').reshape((1,)))
        # constant_26: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_26', torch.tensor(
            [0, 1, 2, 3],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_28: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_28', torch.tensor(
            [4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_30: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_30', torch.tensor(
            [8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((4,)))
        # constant_32: shape=(4,), dtype=torch.int64
        self.register_buffer('constant_32', torch.tensor(
            [12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((4,)))

    @property
    def param_weight_ih_l0(self):
        return self.source.weight_ih_l0

    @property
    def param_bias_ih_l0(self):
        return self.source.bias_ih_l0

    @property
    def param_weight_hh_l0(self):
        return self.source.weight_hh_l0

    @property
    def param_bias_hh_l0(self):
        return self.source.bias_hh_l0


class LSTM(ExpandedModule):
    definition_type = LSTMParameterDefinition

    def forward(self, x, state):
        # ROUTE -> (1, 2, 4)
        node_3 = d.route(state[0], self.p.constant_4, dim=0)
        # RESHAPE -> (2, 4)
        node_5 = d.reshape(node_3, [2, 4])
        # ROUTE -> (1, 2, 4)
        node_6 = d.route(state[1], self.p.constant_7, dim=0)
        # RESHAPE -> (2, 4)
        node_8 = d.reshape(node_6, [2, 4])
        # SCAN -> ((3, 2, 4), ((2, 4), (2, 4)))
        node_42 = d.LOOP.SCAN(
            self.node_42_body,
            x,
            (node_5, node_8),
            domain=self.p.domain_node_42,
            parameters=None,
        )
        # RESHAPE -> (1, 2, 4)
        node_43 = d.reshape(node_42[1][0], (1, 2, 4))
        # RESHAPE -> (1, 2, 4)
        node_44 = d.reshape(node_42[1][1], (1, 2, 4))
        return (node_42[0], (node_43, node_44))

    def node_42_body(self, fragment, carry, parameters):
        # PERMUTE -> (3, 16)
        node_12 = d.permute(self.p.param_weight_ih_l0, (1, 0))
        # PROJECT -> (2, 16)
        node_14 = d.project(fragment, node_12)
        # BROADCAST -> (2, 16)
        node_15 = d.broadcast(self.p.param_bias_ih_l0, (2, 16))
        # ADD -> (2, 16)
        node_17 = d.add(node_14, node_15)
        # PERMUTE -> (4, 16)
        node_18 = d.permute(self.p.param_weight_hh_l0, (1, 0))
        # PROJECT -> (2, 16)
        node_20 = d.project(carry[0], node_18)
        # BROADCAST -> (2, 16)
        node_21 = d.broadcast(self.p.param_bias_hh_l0, (2, 16))
        # ADD -> (2, 16)
        node_23 = d.add(node_20, node_21)
        # ADD -> (2, 16)
        node_24 = d.add(node_17, node_23)
        # ROUTE -> (2, 4)
        node_25 = d.route(node_24, self.p.constant_26, dim=-1)
        # ROUTE -> (2, 4)
        node_27 = d.route(node_24, self.p.constant_28, dim=-1)
        # ROUTE -> (2, 4)
        node_29 = d.route(node_24, self.p.constant_30, dim=-1)
        # ROUTE -> (2, 4)
        node_31 = d.route(node_24, self.p.constant_32, dim=-1)
        # NONLINEAR -> (2, 4)
        node_33 = d.nonlinear(node_25, activation='sigmoid')
        # NONLINEAR -> (2, 4)
        node_34 = d.nonlinear(node_27, activation='sigmoid')
        # NONLINEAR -> (2, 4)
        node_35 = d.nonlinear(node_29, activation='tanh')
        # NONLINEAR -> (2, 4)
        node_36 = d.nonlinear(node_31, activation='sigmoid')
        # MUL -> (2, 4)
        node_37 = d.mul(node_34, carry[1])
        # MUL -> (2, 4)
        node_38 = d.mul(node_33, node_35)
        # ADD -> (2, 4)
        node_39 = d.add(node_37, node_38)
        # NONLINEAR -> (2, 4)
        node_40 = d.nonlinear(node_39, activation='tanh')
        # MUL -> (2, 4)
        node_41 = d.mul(node_36, node_40)
        return (node_41, (node_41, node_39))
