"""MarginRankingLoss: expanded primitive implementation for MarginRankingLoss.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class MarginRankingLossParameterDefinition(ExpandedParameterDefinition):
    public_name = 'MarginRankingLoss'
    source_repr = 'MarginRankingLoss()'
    source_configuration = (('', 'torch.nn.modules.loss', 'MarginRankingLoss', (('margin', 0.2), ('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 3), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_4: shape=(), dtype=torch.float64
        self.register_buffer('constant_4', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(), dtype=torch.float64
        self.register_buffer('constant_9', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_12: shape=(), dtype=torch.float64
        self.register_buffer('constant_12', torch.tensor(
            0.2,
            dtype=torch.float64, device='cpu').reshape(()))


class MarginRankingLoss(ExpandedModule):
    definition_type = MarginRankingLossParameterDefinition

    def forward(self, x1, x2, target):
        # BROADCAST -> (2, 3)
        node_3 = d.broadcast(self.p.constant_4, (2, 3))
        # MUL -> (2, 3)
        node_5 = d.mul(x2, node_3)
        # ADD -> (2, 3)
        node_6 = d.add(x1, node_5)
        # MUL -> (2, 3)
        node_7 = d.mul(target, node_6)
        # BROADCAST -> (2, 3)
        node_8 = d.broadcast(self.p.constant_9, (2, 3))
        # MUL -> (2, 3)
        node_10 = d.mul(node_7, node_8)
        # BROADCAST -> (2, 3)
        node_11 = d.broadcast(self.p.constant_12, (2, 3))
        # ADD -> (2, 3)
        node_13 = d.add(node_10, node_11)
        # NONLINEAR -> (2, 3)
        node_14 = d.nonlinear(node_13)
        # REDUCE -> ()
        node_15 = d.reduce(node_14, dim=(0, 1), reducer='mean')
        return node_15
