"""MaxUnpool2d: expanded primitive implementation for MaxUnpool2d.

Configuration: non-overlapping pool-produced indices; one-hot incidence via ROUTE
Limitations: Only unique destination indices, no duplicate-write semantics; dense one-hot expansion is not an efficient implementation.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class MaxUnpool2dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'MaxUnpool2d'
    source_repr = 'MaxUnpool2d(kernel_size=(2, 2), stride=(2, 2), padding=(0, 0))'
    source_configuration = (('', 'torch.nn.modules.pooling', 'MaxUnpool2d', (('kernel_size', (2, 2)), ('padding', (0, 0)), ('stride', (2, 2)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 2, 2), torch.float64, torch.device('cpu')), TensorSpec((2, 3, 2, 2), torch.int64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_4: shape=(16, 16), dtype=torch.float64
        self.register_buffer('constant_4', torch.tensor(
            [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]],
            dtype=torch.float64, device='cpu').reshape((16, 16)))


class MaxUnpool2d(ExpandedModule):
    definition_type = MaxUnpool2dParameterDefinition

    def forward(self, values, indices):
        # RESHAPE -> (2, 3, 4)
        node_2 = d.reshape(indices, (2, 3, 4))
        # ROUTE -> (2, 3, 4, 16)
        node_3 = d.route(self.p.constant_4, node_2, dim=0)
        # RESHAPE -> (2, 3, 4, 1)
        node_5 = d.reshape(values, (2, 3, 4, 1))
        # BROADCAST -> (2, 3, 4, 16)
        node_6 = d.broadcast(node_5, (2, 3, 4, 16))
        # MUL -> (2, 3, 4, 16)
        node_7 = d.mul(node_3, node_6)
        # REDUCE -> (2, 3, 16)
        node_8 = d.reduce(node_7, dim=-2)
        # RESHAPE -> (2, 3, 4, 4)
        node_9 = d.reshape(node_8, (2, 3, 4, 4))
        return node_9
