"""MultiLabelMarginLoss: expanded primitive implementation for MultiLabelMarginLoss.

Configuration: default reductions, valid labels; no class weights/ignore_index
Limitations: Index-selection lowering can create quadratic intermediates; no sparse-gradient or ignored-label contract.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class MultiLabelMarginLossParameterDefinition(ExpandedParameterDefinition):
    public_name = 'MultiLabelMarginLoss'
    source_repr = 'MultiLabelMarginLoss()'
    source_configuration = (('', 'torch.nn.modules.loss', 'MultiLabelMarginLoss', (('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 3), torch.int64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(3, 3), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
            dtype=torch.float64, device='cpu').reshape((3, 3)))
        # constant_10: shape=(), dtype=torch.float64
        self.register_buffer('constant_10', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_14: shape=(), dtype=torch.float64
        self.register_buffer('constant_14', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_20: shape=(), dtype=torch.float64
        self.register_buffer('constant_20', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_22: shape=(), dtype=torch.float64
        self.register_buffer('constant_22', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_31: shape=(), dtype=torch.float64
        self.register_buffer('constant_31', torch.tensor(
            0.3333333333333333,
            dtype=torch.float64, device='cpu').reshape(()))


class MultiLabelMarginLoss(ExpandedModule):
    definition_type = MultiLabelMarginLossParameterDefinition

    def forward(self, x, target):
        # ROUTE -> (2, 3, 3)
        node_2 = d.route(self.p.constant_3, target, dim=0, padding='zero')
        # AGGREGATE -> (2, 3)
        node_4 = d.aggregate(node_2)
        # RESHAPE -> (2, 3, 1)
        node_5 = d.reshape(x, (2, 3, 1))
        # BROADCAST -> (2, 3, 3)
        node_6 = d.broadcast(node_5, (2, 3, 3))
        # RESHAPE -> (2, 1, 3)
        node_7 = d.reshape(x, (2, 1, 3))
        # BROADCAST -> (2, 3, 3)
        node_8 = d.broadcast(node_7, (2, 3, 3))
        # BROADCAST -> (2, 3, 3)
        node_9 = d.broadcast(self.p.constant_10, (2, 3, 3))
        # MUL -> (2, 3, 3)
        node_11 = d.mul(node_6, node_9)
        # ADD -> (2, 3, 3)
        node_12 = d.add(node_8, node_11)
        # BROADCAST -> (2, 3, 3)
        node_13 = d.broadcast(self.p.constant_14, (2, 3, 3))
        # ADD -> (2, 3, 3)
        node_15 = d.add(node_12, node_13)
        # NONLINEAR -> (2, 3, 3)
        node_16 = d.nonlinear(node_15)
        # RESHAPE -> (2, 3, 1)
        node_17 = d.reshape(node_4, (2, 3, 1))
        # BROADCAST -> (2, 3, 3)
        node_18 = d.broadcast(node_17, (2, 3, 3))
        # BROADCAST -> (2, 3)
        node_19 = d.broadcast(self.p.constant_20, (2, 3))
        # BROADCAST -> (2, 3)
        node_21 = d.broadcast(self.p.constant_22, (2, 3))
        # MUL -> (2, 3)
        node_23 = d.mul(node_4, node_21)
        # ADD -> (2, 3)
        node_24 = d.add(node_19, node_23)
        # RESHAPE -> (2, 1, 3)
        node_25 = d.reshape(node_24, (2, 1, 3))
        # BROADCAST -> (2, 3, 3)
        node_26 = d.broadcast(node_25, (2, 3, 3))
        # MUL -> (2, 3, 3)
        node_27 = d.mul(node_16, node_18)
        # MUL -> (2, 3, 3)
        node_28 = d.mul(node_27, node_26)
        # REDUCE -> (2,)
        node_29 = d.reduce(node_28, dim=(1, 2))
        # BROADCAST -> (2,)
        node_30 = d.broadcast(self.p.constant_31, (2,))
        # MUL -> (2,)
        node_32 = d.mul(node_29, node_30)
        # REDUCE -> ()
        node_33 = d.reduce(node_32, dim=(0,), reducer='mean')
        return node_33
