"""MultiMarginLoss: expanded primitive implementation for MultiMarginLoss.

Configuration: default reductions, valid labels; no class weights/ignore_index
Limitations: Index-selection lowering can create quadratic intermediates; no sparse-gradient or ignored-label contract.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class MultiMarginLossParameterDefinition(ExpandedParameterDefinition):
    public_name = 'MultiMarginLoss'
    source_repr = 'MultiMarginLoss()'
    source_configuration = (('', 'torch.nn.modules.loss', 'MultiMarginLoss', (('margin', 1.0), ('p', 1), ('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2,), torch.int64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_6: shape=(2,), dtype=torch.int64
        self.register_buffer('constant_6', torch.tensor(
            [0, 3],
            dtype=torch.int64, device='cpu').reshape((2,)))
        # constant_10: shape=(), dtype=torch.float64
        self.register_buffer('constant_10', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_14: shape=(), dtype=torch.float64
        self.register_buffer('constant_14', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_19: shape=(), dtype=torch.float64
        self.register_buffer('constant_19', torch.tensor(
            1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_21: shape=(), dtype=torch.float64
        self.register_buffer('constant_21', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_25: shape=(), dtype=torch.float64
        self.register_buffer('constant_25', torch.tensor(
            0.3333333333333333,
            dtype=torch.float64, device='cpu').reshape(()))


class MultiMarginLoss(ExpandedModule):
    definition_type = MultiMarginLossParameterDefinition

    def forward(self, x, target):
        # PERMUTE -> (3, 2)
        node_2 = d.permute(x, (1, 0))
        # ROUTE -> (2, 2)
        node_3 = d.route(node_2, target, dim=0)
        # RESHAPE -> (4,)
        node_4 = d.reshape(node_3, (-1,))
        # ROUTE -> (2,)
        node_5 = d.route(node_4, self.p.constant_6, dim=0)
        # RESHAPE -> (2, 1)
        node_7 = d.reshape(node_5, (2, 1))
        # BROADCAST -> (2, 3)
        node_8 = d.broadcast(node_7, (2, 3))
        # BROADCAST -> (2, 3)
        node_9 = d.broadcast(self.p.constant_10, (2, 3))
        # MUL -> (2, 3)
        node_11 = d.mul(node_8, node_9)
        # ADD -> (2, 3)
        node_12 = d.add(x, node_11)
        # BROADCAST -> (2, 3)
        node_13 = d.broadcast(self.p.constant_14, (2, 3))
        # ADD -> (2, 3)
        node_15 = d.add(node_12, node_13)
        # NONLINEAR -> (2, 3)
        node_16 = d.nonlinear(node_15)
        # REDUCE -> (2,)
        node_17 = d.reduce(node_16, dim=-1)
        # BROADCAST -> (2,)
        node_18 = d.broadcast(self.p.constant_19, (2,))
        # BROADCAST -> (2,)
        node_20 = d.broadcast(self.p.constant_21, (2,))
        # MUL -> (2,)
        node_22 = d.mul(node_18, node_20)
        # ADD -> (2,)
        node_23 = d.add(node_17, node_22)
        # BROADCAST -> (2,)
        node_24 = d.broadcast(self.p.constant_25, (2,))
        # MUL -> (2,)
        node_26 = d.mul(node_23, node_24)
        # REDUCE -> ()
        node_27 = d.reduce(node_26, dim=(0,), reducer='mean')
        return node_27
