"""MultiheadAttention: expanded primitive implementation for MultiheadAttention.

Configuration: 2 heads, self-attention, batch_first, dropout=0
Limitations: No masks, separate kdim/vdim, bias_kv, zero-attention or training dropout in this fixture.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class MultiheadAttentionParameterDefinition(ExpandedParameterDefinition):
    public_name = 'MultiheadAttention'
    source_repr = 'MultiheadAttention(\n  (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)\n)'
    source_configuration = (('', 'torch.nn.modules.activation', 'MultiheadAttention', (('add_zero_attn', False), ('batch_first', True), ('bias_k', None), ('bias_v', None), ('dropout', 0.0), ('embed_dim', 8), ('head_dim', 4), ('kdim', 8), ('num_heads', 2), ('training', True), ('vdim', 8))), ('out_proj', 'torch.nn.modules.linear', 'NonDynamicallyQuantizableLinear', (('in_features', 8), ('out_features', 8), ('training', True))))
    frozen_buffers = {}
    source_modes = (('', True), ('out_proj', True))
    input_specs = (TensorSpec((2, 3, 8), torch.float64, torch.device('cpu')), TensorSpec((2, 3, 8), torch.float64, torch.device('cpu')), TensorSpec((2, 3, 8), torch.float64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_5: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_5', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_7: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_7', torch.tensor(
            [8, 9, 10, 11, 12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_9: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [16, 17, 18, 19, 20, 21, 22, 23],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_12: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_12', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_14: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_14', torch.tensor(
            [8, 9, 10, 11, 12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_16: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_16', torch.tensor(
            [16, 17, 18, 19, 20, 21, 22, 23],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_37: shape=(), dtype=torch.float64
        self.register_buffer('constant_37', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))

    @property
    def param_in_proj_weight(self):
        return self.source.in_proj_weight

    @property
    def param_in_proj_bias(self):
        return self.source.in_proj_bias

    @property
    def param_out_proj_weight(self):
        return self.source.out_proj.weight

    @property
    def param_out_proj_bias(self):
        return self.source.out_proj.bias


class MultiheadAttention(ExpandedModule):
    definition_type = MultiheadAttentionParameterDefinition

    def forward(self, q, k, v):
        # ROUTE -> (8, 8)
        node_3 = d.route(self.p.param_in_proj_weight, self.p.constant_5, dim=0)
        # ROUTE -> (8, 8)
        node_6 = d.route(self.p.param_in_proj_weight, self.p.constant_7, dim=0)
        # ROUTE -> (8, 8)
        node_8 = d.route(self.p.param_in_proj_weight, self.p.constant_9, dim=0)
        # ROUTE -> (8,)
        node_10 = d.route(self.p.param_in_proj_bias, self.p.constant_12, dim=0)
        # ROUTE -> (8,)
        node_13 = d.route(self.p.param_in_proj_bias, self.p.constant_14, dim=0)
        # ROUTE -> (8,)
        node_15 = d.route(self.p.param_in_proj_bias, self.p.constant_16, dim=0)
        # PERMUTE -> (8, 8)
        node_17 = d.permute(node_3, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_18 = d.project(q, node_17)
        # BROADCAST -> (2, 3, 8)
        node_19 = d.broadcast(node_10, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_20 = d.add(node_18, node_19)
        # PERMUTE -> (8, 8)
        node_21 = d.permute(node_6, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_22 = d.project(k, node_21)
        # BROADCAST -> (2, 3, 8)
        node_23 = d.broadcast(node_13, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_24 = d.add(node_22, node_23)
        # PERMUTE -> (8, 8)
        node_25 = d.permute(node_8, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_26 = d.project(v, node_25)
        # BROADCAST -> (2, 3, 8)
        node_27 = d.broadcast(node_15, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_28 = d.add(node_26, node_27)
        # RESHAPE -> (2, 3, 2, 4)
        node_29 = d.reshape(node_20, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_30 = d.permute(node_29, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 2, 4)
        node_31 = d.reshape(node_24, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_32 = d.permute(node_31, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 2, 4)
        node_33 = d.reshape(node_28, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_34 = d.permute(node_33, (0, 2, 1, 3))
        # COMPARE -> (2, 2, 3, 3)
        node_35 = d.compare(node_30, node_32)
        # BROADCAST -> (2, 2, 3, 3)
        node_36 = d.broadcast(self.p.constant_37, (2, 2, 3, 3))
        # MUL -> (2, 2, 3, 3)
        node_38 = d.mul(node_35, node_36)
        # NORMALIZE -> (2, 2, 3, 3)
        node_39 = d.normalize(node_38)
        # MIX -> (2, 2, 3, 4)
        node_40 = d.mix(node_34, node_39)
        # PERMUTE -> (2, 3, 2, 4)
        node_41 = d.permute(node_40, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 8)
        node_42 = d.reshape(node_41, (2, 3, 8))
        # PERMUTE -> (8, 8)
        node_43 = d.permute(self.p.param_out_proj_weight, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_45 = d.project(node_42, node_43)
        # BROADCAST -> (2, 3, 8)
        node_46 = d.broadcast(self.p.param_out_proj_bias, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_48 = d.add(node_45, node_46)
        # REDUCE -> (2, 3, 3)
        node_49 = d.reduce(node_39, dim=1, reducer='mean')
        return (node_48, node_49)
