"""NLLLoss2d: expanded primitive implementation for NLLLoss2d.

Configuration: default reductions, valid labels; no class weights/ignore_index
Limitations: Index-selection lowering can create quadratic intermediates; no sparse-gradient or ignored-label contract.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class NLLLoss2dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'NLLLoss2d'
    source_repr = 'NLLLoss2d()'
    source_configuration = (('', 'torch.nn.modules.loss', 'NLLLoss2d', (('ignore_index', -100), ('reduction', 'mean'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 2, 2), torch.float64, torch.device('cpu')), TensorSpec((2, 2, 2), torch.int64, torch.device('cpu')))
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_9: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_9', torch.tensor(
            [0, 9, 18, 27, 36, 45, 54, 63],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_11: shape=(), dtype=torch.float64
        self.register_buffer('constant_11', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class NLLLoss2d(ExpandedModule):
    definition_type = NLLLoss2dParameterDefinition

    def forward(self, x, target):
        # PERMUTE -> (2, 2, 2, 3)
        node_2 = d.permute(x, (0, 2, 3, 1))
        # RESHAPE -> (8, 3)
        node_3 = d.reshape(node_2, (-1, 3))
        # RESHAPE -> (8,)
        node_4 = d.reshape(target, (-1,))
        # PERMUTE -> (3, 8)
        node_5 = d.permute(node_3, (1, 0))
        # ROUTE -> (8, 8)
        node_6 = d.route(node_5, node_4, dim=0)
        # RESHAPE -> (64,)
        node_7 = d.reshape(node_6, (-1,))
        # ROUTE -> (8,)
        node_8 = d.route(node_7, self.p.constant_9, dim=0)
        # BROADCAST -> (8,)
        node_10 = d.broadcast(self.p.constant_11, (8,))
        # MUL -> (8,)
        node_12 = d.mul(node_8, node_10)
        # RESHAPE -> (2, 2, 2)
        node_13 = d.reshape(node_12, (2, 2, 2))
        # REDUCE -> ()
        node_14 = d.reduce(node_13, dim=(0, 1, 2), reducer='mean')
        return node_14
