"""PixelUnshuffle: expanded primitive implementation for PixelUnshuffle.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class PixelUnshuffleParameterDefinition(ExpandedParameterDefinition):
    public_name = 'PixelUnshuffle'
    source_repr = 'PixelUnshuffle(downscale_factor=2)'
    source_configuration = (('', 'torch.nn.modules.pixelshuffle', 'PixelUnshuffle', (('downscale_factor', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 4, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False


class PixelUnshuffle(ExpandedModule):
    definition_type = PixelUnshuffleParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 4, 2, 2, 2, 2)
        node_1 = d.reshape(x, (2, 4, 2, 2, 2, 2))
        # PERMUTE -> (2, 4, 2, 2, 2, 2)
        node_2 = d.permute(node_1, (0, 1, 3, 5, 2, 4))
        # RESHAPE -> (2, 16, 2, 2)
        node_3 = d.reshape(node_2, (2, 16, 2, 2))
        return node_3
