"""PixelShuffle: expanded primitive implementation for PixelShuffle.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class PixelShuffleParameterDefinition(ExpandedParameterDefinition):
    public_name = 'PixelShuffle'
    source_repr = 'PixelShuffle(upscale_factor=2)'
    source_configuration = (('', 'torch.nn.modules.pixelshuffle', 'PixelShuffle', (('training', True), ('upscale_factor', 2))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 8, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False


class PixelShuffle(ExpandedModule):
    definition_type = PixelShuffleParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 2, 2, 2, 4, 4)
        node_1 = d.reshape(x, (2, 2, 2, 2, 4, 4))
        # PERMUTE -> (2, 2, 4, 2, 4, 2)
        node_2 = d.permute(node_1, (0, 1, 4, 2, 5, 3))
        # RESHAPE -> (2, 2, 8, 8)
        node_3 = d.reshape(node_2, (2, 2, 8, 8))
        return node_3
