"""PReLU: expanded primitive implementation for PReLU.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class PReLUParameterDefinition(ExpandedParameterDefinition):
    public_name = 'PReLU'
    source_repr = 'PReLU(num_parameters=3)'
    source_configuration = (('', 'torch.nn.modules.activation', 'PReLU', (('init', 0.25), ('num_parameters', 3), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_7: shape=(), dtype=torch.float64
        self.register_buffer('constant_7', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))

    @property
    def param_weight(self):
        return self.source.weight


class PReLU(ExpandedModule):
    definition_type = PReLUParameterDefinition

    def forward(self, x):
        # NONLINEAR -> (2, 3, 4)
        node_1 = d.nonlinear(x)
        # BROADCAST -> (2, 3, 4)
        node_2 = d.broadcast(self.p.constant_3, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_4 = d.mul(x, node_2)
        # NONLINEAR -> (2, 3, 4)
        node_5 = d.nonlinear(node_4)
        # BROADCAST -> (2, 3, 4)
        node_6 = d.broadcast(self.p.constant_7, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_8 = d.mul(node_5, node_6)
        # RESHAPE -> (1, 3, 1)
        node_9 = d.reshape(self.p.param_weight, (1, 3, 1))
        # BROADCAST -> (2, 3, 4)
        node_11 = d.broadcast(node_9, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_12 = d.mul(node_8, node_11)
        # ADD -> (2, 3, 4)
        node_13 = d.add(node_1, node_12)
        return node_13
