"""ReflectionPad3d: expanded primitive implementation for ReflectionPad3d.

Configuration: asymmetric positive padding (1,2) per axis
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ReflectionPad3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ReflectionPad3d'
    source_repr = 'ReflectionPad3d((1, 2, 1, 2, 1, 2))'
    source_configuration = (('', 'torch.nn.modules.padding', 'ReflectionPad3d', (('padding', (1, 2, 1, 2, 1, 2)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(343,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [21, 20, 21, 22, 23, 22, 21, 17, 16, 17, 18, 19, 18, 17, 21, 20, 21, 22, 23, 22, 21, 25,
             24, 25, 26, 27, 26, 25, 29, 28, 29, 30, 31, 30, 29, 25, 24, 25, 26, 27, 26, 25, 21, 20,
             21, 22, 23, 22, 21, 5, 4, 5, 6, 7, 6, 5, 1, 0, 1, 2, 3, 2, 1, 5, 4, 5, 6, 7, 6, 5, 9, 8,
             9, 10, 11, 10, 9, 13, 12, 13, 14, 15, 14, 13, 9, 8, 9, 10, 11, 10, 9, 5, 4, 5, 6, 7, 6,
             5, 21, 20, 21, 22, 23, 22, 21, 17, 16, 17, 18, 19, 18, 17, 21, 20, 21, 22, 23, 22, 21,
             25, 24, 25, 26, 27, 26, 25, 29, 28, 29, 30, 31, 30, 29, 25, 24, 25, 26, 27, 26, 25, 21,
             20, 21, 22, 23, 22, 21, 37, 36, 37, 38, 39, 38, 37, 33, 32, 33, 34, 35, 34, 33, 37, 36,
             37, 38, 39, 38, 37, 41, 40, 41, 42, 43, 42, 41, 45, 44, 45, 46, 47, 46, 45, 41, 40, 41,
             42, 43, 42, 41, 37, 36, 37, 38, 39, 38, 37, 53, 52, 53, 54, 55, 54, 53, 49, 48, 49, 50,
             51, 50, 49, 53, 52, 53, 54, 55, 54, 53, 57, 56, 57, 58, 59, 58, 57, 61, 60, 61, 62, 63,
             62, 61, 57, 56, 57, 58, 59, 58, 57, 53, 52, 53, 54, 55, 54, 53, 37, 36, 37, 38, 39, 38,
             37, 33, 32, 33, 34, 35, 34, 33, 37, 36, 37, 38, 39, 38, 37, 41, 40, 41, 42, 43, 42, 41,
             45, 44, 45, 46, 47, 46, 45, 41, 40, 41, 42, 43, 42, 41, 37, 36, 37, 38, 39, 38, 37, 21,
             20, 21, 22, 23, 22, 21, 17, 16, 17, 18, 19, 18, 17, 21, 20, 21, 22, 23, 22, 21, 25, 24,
             25, 26, 27, 26, 25, 29, 28, 29, 30, 31, 30, 29, 25, 24, 25, 26, 27, 26, 25, 21, 20, 21,
             22, 23, 22, 21],
            dtype=torch.int64, device='cpu').reshape((343,)))


class ReflectionPad3d(ExpandedModule):
    definition_type = ReflectionPad3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 64)
        node_1 = d.reshape(x, (2, 3, 64))
        # ROUTE -> (2, 3, 343)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # RESHAPE -> (2, 3, 7, 7, 7)
        node_4 = d.reshape(node_2, (2, 3, 7, 7, 7))
        return node_4
