"""ReflectionPad2d: expanded primitive implementation for ReflectionPad2d.

Configuration: asymmetric positive padding (1,2) per axis
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ReflectionPad2dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ReflectionPad2d'
    source_repr = 'ReflectionPad2d((1, 2, 1, 2))'
    source_configuration = (('', 'torch.nn.modules.padding', 'ReflectionPad2d', (('padding', (1, 2, 1, 2)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(49,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [5, 4, 5, 6, 7, 6, 5, 1, 0, 1, 2, 3, 2, 1, 5, 4, 5, 6, 7, 6, 5, 9, 8, 9, 10, 11, 10, 9,
             13, 12, 13, 14, 15, 14, 13, 9, 8, 9, 10, 11, 10, 9, 5, 4, 5, 6, 7, 6, 5],
            dtype=torch.int64, device='cpu').reshape((49,)))


class ReflectionPad2d(ExpandedModule):
    definition_type = ReflectionPad2dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 16)
        node_1 = d.reshape(x, (2, 3, 16))
        # ROUTE -> (2, 3, 49)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # RESHAPE -> (2, 3, 7, 7)
        node_4 = d.reshape(node_2, (2, 3, 7, 7))
        return node_4
