"""ReflectionPad1d: expanded primitive implementation for ReflectionPad1d.

Configuration: asymmetric positive padding (1,2) per axis
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ReflectionPad1dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ReflectionPad1d'
    source_repr = 'ReflectionPad1d((1, 2))'
    source_configuration = (('', 'torch.nn.modules.padding', 'ReflectionPad1d', (('padding', (1, 2)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(7,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [1, 0, 1, 2, 3, 2, 1],
            dtype=torch.int64, device='cpu').reshape((7,)))


class ReflectionPad1d(ExpandedModule):
    definition_type = ReflectionPad1dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 4)
        node_1 = d.reshape(x, (2, 3, 4))
        # ROUTE -> (2, 3, 7)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # RESHAPE -> (2, 3, 7)
        node_4 = d.reshape(node_2, (2, 3, 7))
        return node_4
