"""ReplicationPad3d: expanded primitive implementation for ReplicationPad3d.

Configuration: asymmetric positive padding (1,2) per axis
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ReplicationPad3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ReplicationPad3d'
    source_repr = 'ReplicationPad3d((1, 2, 1, 2, 1, 2))'
    source_configuration = (('', 'torch.nn.modules.padding', 'ReplicationPad3d', (('padding', (1, 2, 1, 2, 1, 2)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(343,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 0, 1, 2, 3, 3, 3, 0, 0, 1, 2, 3, 3, 3, 4, 4, 5, 6, 7, 7, 7, 8, 8, 9, 10, 11, 11, 11,
             12, 12, 13, 14, 15, 15, 15, 12, 12, 13, 14, 15, 15, 15, 12, 12, 13, 14, 15, 15, 15, 0, 0,
             1, 2, 3, 3, 3, 0, 0, 1, 2, 3, 3, 3, 4, 4, 5, 6, 7, 7, 7, 8, 8, 9, 10, 11, 11, 11, 12, 12,
             13, 14, 15, 15, 15, 12, 12, 13, 14, 15, 15, 15, 12, 12, 13, 14, 15, 15, 15, 16, 16, 17,
             18, 19, 19, 19, 16, 16, 17, 18, 19, 19, 19, 20, 20, 21, 22, 23, 23, 23, 24, 24, 25, 26,
             27, 27, 27, 28, 28, 29, 30, 31, 31, 31, 28, 28, 29, 30, 31, 31, 31, 28, 28, 29, 30, 31,
             31, 31, 32, 32, 33, 34, 35, 35, 35, 32, 32, 33, 34, 35, 35, 35, 36, 36, 37, 38, 39, 39,
             39, 40, 40, 41, 42, 43, 43, 43, 44, 44, 45, 46, 47, 47, 47, 44, 44, 45, 46, 47, 47, 47,
             44, 44, 45, 46, 47, 47, 47, 48, 48, 49, 50, 51, 51, 51, 48, 48, 49, 50, 51, 51, 51, 52,
             52, 53, 54, 55, 55, 55, 56, 56, 57, 58, 59, 59, 59, 60, 60, 61, 62, 63, 63, 63, 60, 60,
             61, 62, 63, 63, 63, 60, 60, 61, 62, 63, 63, 63, 48, 48, 49, 50, 51, 51, 51, 48, 48, 49,
             50, 51, 51, 51, 52, 52, 53, 54, 55, 55, 55, 56, 56, 57, 58, 59, 59, 59, 60, 60, 61, 62,
             63, 63, 63, 60, 60, 61, 62, 63, 63, 63, 60, 60, 61, 62, 63, 63, 63, 48, 48, 49, 50, 51,
             51, 51, 48, 48, 49, 50, 51, 51, 51, 52, 52, 53, 54, 55, 55, 55, 56, 56, 57, 58, 59, 59,
             59, 60, 60, 61, 62, 63, 63, 63, 60, 60, 61, 62, 63, 63, 63, 60, 60, 61, 62, 63, 63, 63],
            dtype=torch.int64, device='cpu').reshape((343,)))


class ReplicationPad3d(ExpandedModule):
    definition_type = ReplicationPad3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 64)
        node_1 = d.reshape(x, (2, 3, 64))
        # ROUTE -> (2, 3, 343)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # RESHAPE -> (2, 3, 7, 7, 7)
        node_4 = d.reshape(node_2, (2, 3, 7, 7, 7))
        return node_4
