"""RMSNorm: expanded primitive implementation for RMSNorm.

Configuration: two trailing normalized axes; eps=1e-5
Limitations: RMSNorm lowered using NORM([x,-x]) then selecting the first half; no new primitive.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class RMSNormParameterDefinition(ExpandedParameterDefinition):
    public_name = 'RMSNorm'
    source_repr = 'RMSNorm((3, 4), eps=1e-05, elementwise_affine=True)'
    source_configuration = (('', 'torch.nn.modules.normalization', 'RMSNorm', (('elementwise_affine', True), ('eps', 1e-05), ('normalized_shape', (3, 4)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_8: shape=(12,), dtype=torch.int64
        self.register_buffer('constant_8', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            dtype=torch.int64, device='cpu').reshape((12,)))

    @property
    def param_weight(self):
        return self.source.weight


class RMSNorm(ExpandedModule):
    definition_type = RMSNormParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 12)
        node_1 = d.reshape(x, (2, 12))
        # BROADCAST -> (2, 12)
        node_2 = d.broadcast(self.p.constant_3, (2, 12))
        # MUL -> (2, 12)
        node_4 = d.mul(node_1, node_2)
        # CONCAT -> (2, 24)
        node_5 = d.concat((node_1, node_4), dim=-1)
        # NORM -> (2, 24)
        node_6 = d.norm(node_5, eps=1e-05)
        # ROUTE -> (2, 12)
        node_7 = d.route(node_6, self.p.constant_8, dim=-1)
        # RESHAPE -> (2, 3, 4)
        node_9 = d.reshape(node_7, (2, 3, 4))
        # BROADCAST -> (2, 3, 4)
        node_10 = d.broadcast(self.p.param_weight, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_12 = d.mul(node_9, node_10)
        return node_12
