"""RNN: expanded primitive implementation for RNN.

Configuration: one layer, one direction, T=3, no dropout or packed sequence
Limitations: PackedSequence, projected LSTM, multi-layer/bidirectional combinations not included.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class RNNParameterDefinition(ExpandedParameterDefinition):
    public_name = 'RNN'
    source_repr = 'RNN(3, 4)'
    source_configuration = (('', 'torch.nn.modules.rnn', 'RNN', (('batch_first', False), ('bias', True), ('bidirectional', False), ('dropout', 0.0), ('hidden_size', 4), ('input_size', 3), ('mode', 'RNN_TANH'), ('nonlinearity', 'tanh'), ('num_layers', 1), ('proj_size', 0), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((3, 2, 3), torch.float64, torch.device('cpu')), TensorSpec((1, 2, 4), torch.float64, torch.device('cpu')))
    stateless = False

    domain_node_21 = {'axis': 0, 'out_dim': 0, 'reverse': False, 'kind': 'sequence'}

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(1,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0],
            dtype=torch.int64, device='cpu').reshape((1,)))

    @property
    def param_weight_ih_l0(self):
        return self.source.weight_ih_l0

    @property
    def param_bias_ih_l0(self):
        return self.source.bias_ih_l0

    @property
    def param_weight_hh_l0(self):
        return self.source.weight_hh_l0

    @property
    def param_bias_hh_l0(self):
        return self.source.bias_hh_l0


class RNN(ExpandedModule):
    definition_type = RNNParameterDefinition

    def forward(self, x, state):
        # ROUTE -> (1, 2, 4)
        node_2 = d.route(state, self.p.constant_3, dim=0)
        # RESHAPE -> (2, 4)
        node_4 = d.reshape(node_2, [2, 4])
        # SCAN -> ((3, 2, 4), (2, 4))
        node_21 = d.LOOP.SCAN(
            self.node_21_body,
            x,
            node_4,
            domain=self.p.domain_node_21,
            parameters=None,
        )
        # RESHAPE -> (1, 2, 4)
        node_22 = d.reshape(node_21[1], (1, 2, 4))
        return (node_21[0], node_22)

    def node_21_body(self, fragment, carry, parameters):
        # PERMUTE -> (3, 4)
        node_7 = d.permute(self.p.param_weight_ih_l0, (1, 0))
        # PROJECT -> (2, 4)
        node_9 = d.project(fragment, node_7)
        # BROADCAST -> (2, 4)
        node_10 = d.broadcast(self.p.param_bias_ih_l0, (2, 4))
        # ADD -> (2, 4)
        node_12 = d.add(node_9, node_10)
        # PERMUTE -> (4, 4)
        node_13 = d.permute(self.p.param_weight_hh_l0, (1, 0))
        # PROJECT -> (2, 4)
        node_15 = d.project(carry, node_13)
        # BROADCAST -> (2, 4)
        node_16 = d.broadcast(self.p.param_bias_hh_l0, (2, 4))
        # ADD -> (2, 4)
        node_18 = d.add(node_15, node_16)
        # ADD -> (2, 4)
        node_19 = d.add(node_12, node_18)
        # NONLINEAR -> (2, 4)
        node_20 = d.nonlinear(node_19, activation='tanh')
        return (node_20, node_20)
