"""RNNCell: expanded primitive implementation for RNNCell.

Configuration: single step; nonzero state; bias=True
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class RNNCellParameterDefinition(ExpandedParameterDefinition):
    public_name = 'RNNCell'
    source_repr = 'RNNCell(3, 4)'
    source_configuration = (('', 'torch.nn.modules.rnn', 'RNNCell', (('bias', True), ('hidden_size', 4), ('input_size', 3), ('nonlinearity', 'tanh'), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')), TensorSpec((2, 4), torch.float64, torch.device('cpu')))
    stateless = False

    @property
    def param_weight_ih(self):
        return self.source.weight_ih

    @property
    def param_bias_ih(self):
        return self.source.bias_ih

    @property
    def param_weight_hh(self):
        return self.source.weight_hh

    @property
    def param_bias_hh(self):
        return self.source.bias_hh


class RNNCell(ExpandedModule):
    definition_type = RNNCellParameterDefinition

    def forward(self, x, state):
        # PERMUTE -> (3, 4)
        node_2 = d.permute(self.p.param_weight_ih, (1, 0))
        # PROJECT -> (2, 4)
        node_4 = d.project(x, node_2)
        # BROADCAST -> (2, 4)
        node_5 = d.broadcast(self.p.param_bias_ih, (2, 4))
        # ADD -> (2, 4)
        node_7 = d.add(node_4, node_5)
        # PERMUTE -> (4, 4)
        node_8 = d.permute(self.p.param_weight_hh, (1, 0))
        # PROJECT -> (2, 4)
        node_10 = d.project(state, node_8)
        # BROADCAST -> (2, 4)
        node_11 = d.broadcast(self.p.param_bias_hh, (2, 4))
        # ADD -> (2, 4)
        node_13 = d.add(node_10, node_11)
        # ADD -> (2, 4)
        node_14 = d.add(node_7, node_13)
        # NONLINEAR -> (2, 4)
        node_15 = d.nonlinear(node_14, activation='tanh')
        return node_15
