"""RReLU: expanded primitive implementation for RReLU.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: RReLU random training slopes not covered.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class RReLUParameterDefinition(ExpandedParameterDefinition):
    public_name = 'RReLU'
    source_repr = 'RReLU(lower=0.125, upper=0.3333333333333333)'
    source_configuration = (('', 'torch.nn.modules.activation', 'RReLU', (('inplace', False), ('lower', 0.125), ('training', False), ('upper', 0.3333333333333333))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_7: shape=(), dtype=torch.float64
        self.register_buffer('constant_7', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_10: shape=(), dtype=torch.float64
        self.register_buffer('constant_10', torch.tensor(
            0.22916666666666666,
            dtype=torch.float64, device='cpu').reshape(()))


class RReLU(ExpandedModule):
    definition_type = RReLUParameterDefinition

    def forward(self, x):
        # NONLINEAR -> (2, 3, 4)
        node_1 = d.nonlinear(x)
        # BROADCAST -> (2, 3, 4)
        node_2 = d.broadcast(self.p.constant_3, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_4 = d.mul(x, node_2)
        # NONLINEAR -> (2, 3, 4)
        node_5 = d.nonlinear(node_4)
        # BROADCAST -> (2, 3, 4)
        node_6 = d.broadcast(self.p.constant_7, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_8 = d.mul(node_5, node_6)
        # BROADCAST -> (2, 3, 4)
        node_9 = d.broadcast(self.p.constant_10, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_11 = d.mul(node_8, node_9)
        # ADD -> (2, 3, 4)
        node_12 = d.add(node_1, node_11)
        return node_12
