"""Sequential: expanded primitive implementation for Sequential.

Configuration: Linear -> ReLU -> Linear
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class SequentialParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Sequential'
    source_repr = 'Sequential(\n  (0): Linear(in_features=3, out_features=4, bias=True)\n  (1): ReLU()\n  (2): Linear(in_features=4, out_features=2, bias=True)\n)'
    source_configuration = (('', 'torch.nn.modules.container', 'Sequential', (('training', True),)), ('0', 'torch.nn.modules.linear', 'Linear', (('in_features', 3), ('out_features', 4), ('training', True))), ('1', 'torch.nn.modules.activation', 'ReLU', (('inplace', False), ('training', True))), ('2', 'torch.nn.modules.linear', 'Linear', (('in_features', 4), ('out_features', 2), ('training', True))))
    frozen_buffers = {}
    source_modes = (('', True), ('0', True), ('1', True), ('2', True))
    input_specs = (TensorSpec((2, 3), torch.float64, torch.device('cpu')),)
    stateless = False

    @property
    def param_0_weight(self):
        return self.source[0].weight

    @property
    def param_0_bias(self):
        return self.source[0].bias

    @property
    def param_2_weight(self):
        return self.source[2].weight

    @property
    def param_2_bias(self):
        return self.source[2].bias


class Sequential(ExpandedModule):
    definition_type = SequentialParameterDefinition

    def forward(self, x):
        # PERMUTE -> (3, 4)
        node_1 = d.permute(self.p.param_0_weight, (1, 0))
        # PROJECT -> (2, 4)
        node_3 = d.project(x, node_1)
        # BROADCAST -> (2, 4)
        node_4 = d.broadcast(self.p.param_0_bias, (2, 4))
        # ADD -> (2, 4)
        node_6 = d.add(node_3, node_4)
        # NONLINEAR -> (2, 4)
        node_7 = d.nonlinear(node_6, activation='relu')
        # PERMUTE -> (4, 2)
        node_8 = d.permute(self.p.param_2_weight, (1, 0))
        # PROJECT -> (2, 2)
        node_10 = d.project(node_7, node_8)
        # BROADCAST -> (2, 2)
        node_11 = d.broadcast(self.p.param_2_bias, (2, 2))
        # ADD -> (2, 2)
        node_13 = d.add(node_10, node_11)
        return node_13
