"""Softmax: expanded primitive implementation for Softmax.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class SoftmaxParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Softmax'
    source_repr = 'Softmax(dim=-1)'
    source_configuration = (('', 'torch.nn.modules.activation', 'Softmax', (('dim', -1), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False


class Softmax(ExpandedModule):
    definition_type = SoftmaxParameterDefinition

    def forward(self, x):
        # NORMALIZE -> (2, 3, 4)
        node_1 = d.normalize(x, dim=-1)
        return node_1
