"""Softmin: expanded primitive implementation for Softmin.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class SoftminParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Softmin'
    source_repr = 'Softmin(dim=-1)'
    source_configuration = (('', 'torch.nn.modules.activation', 'Softmin', (('dim', -1), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_2: shape=(), dtype=torch.float64
        self.register_buffer('constant_2', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class Softmin(ExpandedModule):
    definition_type = SoftminParameterDefinition

    def forward(self, x):
        # BROADCAST -> (2, 3, 4)
        node_1 = d.broadcast(self.p.constant_2, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_3 = d.mul(x, node_1)
        # NORMALIZE -> (2, 3, 4)
        node_4 = d.normalize(node_3, dim=-1)
        return node_4
