"""Softshrink: expanded primitive implementation for Softshrink.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class SoftshrinkParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Softshrink'
    source_repr = 'Softshrink(0.5)'
    source_configuration = (('', 'torch.nn.modules.activation', 'Softshrink', (('lambd', 0.5), ('training', False))),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_2: shape=(), dtype=torch.float64
        self.register_buffer('constant_2', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_4: shape=(), dtype=torch.float64
        self.register_buffer('constant_4', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_9: shape=(), dtype=torch.float64
        self.register_buffer('constant_9', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_12: shape=(), dtype=torch.float64
        self.register_buffer('constant_12', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_14: shape=(), dtype=torch.float64
        self.register_buffer('constant_14', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))
        # constant_19: shape=(), dtype=torch.float64
        self.register_buffer('constant_19', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class Softshrink(ExpandedModule):
    definition_type = SoftshrinkParameterDefinition

    def forward(self, x):
        # BROADCAST -> (2, 3, 4)
        node_1 = d.broadcast(self.p.constant_2, (2, 3, 4))
        # BROADCAST -> (2, 3, 4)
        node_3 = d.broadcast(self.p.constant_4, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_5 = d.mul(node_1, node_3)
        # ADD -> (2, 3, 4)
        node_6 = d.add(x, node_5)
        # NONLINEAR -> (2, 3, 4)
        node_7 = d.nonlinear(node_6)
        # BROADCAST -> (2, 3, 4)
        node_8 = d.broadcast(self.p.constant_9, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_10 = d.mul(x, node_8)
        # BROADCAST -> (2, 3, 4)
        node_11 = d.broadcast(self.p.constant_12, (2, 3, 4))
        # BROADCAST -> (2, 3, 4)
        node_13 = d.broadcast(self.p.constant_14, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_15 = d.mul(node_11, node_13)
        # ADD -> (2, 3, 4)
        node_16 = d.add(node_10, node_15)
        # NONLINEAR -> (2, 3, 4)
        node_17 = d.nonlinear(node_16)
        # BROADCAST -> (2, 3, 4)
        node_18 = d.broadcast(self.p.constant_19, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_20 = d.mul(node_17, node_18)
        # ADD -> (2, 3, 4)
        node_21 = d.add(node_7, node_20)
        return node_21
