"""Tanh: expanded primitive implementation for Tanh.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class TanhParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Tanh'
    source_repr = 'Tanh()'
    source_configuration = (('', 'torch.nn.modules.activation', 'Tanh', (('training', False),)),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False


class Tanh(ExpandedModule):
    definition_type = TanhParameterDefinition

    def forward(self, x):
        # NONLINEAR -> (2, 3, 4)
        node_1 = d.nonlinear(x, activation='tanh')
        return node_1
