"""Tanhshrink: expanded primitive implementation for Tanhshrink.

Configuration: default parameters; RReLU eval; GLU last dim
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class TanhshrinkParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Tanhshrink'
    source_repr = 'Tanhshrink()'
    source_configuration = (('', 'torch.nn.modules.activation', 'Tanhshrink', (('training', False),)),)
    frozen_buffers = {}
    source_modes = (('', False),)
    input_specs = (TensorSpec((2, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            -1.0,
            dtype=torch.float64, device='cpu').reshape(()))


class Tanhshrink(ExpandedModule):
    definition_type = TanhshrinkParameterDefinition

    def forward(self, x):
        # NONLINEAR -> (2, 3, 4)
        node_1 = d.nonlinear(x, activation='tanh')
        # BROADCAST -> (2, 3, 4)
        node_2 = d.broadcast(self.p.constant_3, (2, 3, 4))
        # MUL -> (2, 3, 4)
        node_4 = d.mul(node_1, node_2)
        # ADD -> (2, 3, 4)
        node_5 = d.add(x, node_4)
        return node_5
