"""TransformerEncoderLayer: expanded primitive implementation for TransformerEncoderLayer.

Configuration: small full forward; 1 layer; relu; no masks/dropout
Limitations: Not all Transformer configurations, ragged/nested inputs or generation behavior.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class TransformerEncoderLayerParameterDefinition(ExpandedParameterDefinition):
    public_name = 'TransformerEncoderLayer'
    source_repr = 'TransformerEncoderLayer(\n  (self_attn): MultiheadAttention(\n    (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)\n  )\n  (linear1): Linear(in_features=8, out_features=12, bias=True)\n  (dropout): Dropout(p=0.0, inplace=False)\n  (linear2): Linear(in_features=12, out_features=8, bias=True)\n  (norm1): LayerNorm((8,), eps=1e-05, elementwise_affine=True, bias=True)\n  (norm2): LayerNorm((8,), eps=1e-05, elementwise_affine=True, bias=True)\n  (dropout1): Dropout(p=0.0, inplace=False)\n  (dropout2): Dropout(p=0.0, inplace=False)\n)'
    source_configuration = (('', 'torch.nn.modules.transformer', 'TransformerEncoderLayer', (('activation', 'torch.nn.functional.relu'), ('activation_relu_or_gelu', 1), ('norm_first', False), ('training', False))), ('self_attn', 'torch.nn.modules.activation', 'MultiheadAttention', (('add_zero_attn', False), ('batch_first', True), ('bias_k', None), ('bias_v', None), ('dropout', 0.0), ('embed_dim', 8), ('head_dim', 4), ('kdim', 8), ('num_heads', 2), ('training', False), ('vdim', 8))), ('self_attn.out_proj', 'torch.nn.modules.linear', 'NonDynamicallyQuantizableLinear', (('in_features', 8), ('out_features', 8), ('training', False))), ('linear1', 'torch.nn.modules.linear', 'Linear', (('in_features', 8), ('out_features', 12), ('training', False))), ('dropout', 'torch.nn.modules.dropout', 'Dropout', (('inplace', False), ('p', 0.0), ('training', False))), ('linear2', 'torch.nn.modules.linear', 'Linear', (('in_features', 12), ('out_features', 8), ('training', False))), ('norm1', 'torch.nn.modules.normalization', 'LayerNorm', (('elementwise_affine', True), ('eps', 1e-05), ('normalized_shape', (8,)), ('training', False))), ('norm2', 'torch.nn.modules.normalization', 'LayerNorm', (('elementwise_affine', True), ('eps', 1e-05), ('normalized_shape', (8,)), ('training', False))), ('dropout1', 'torch.nn.modules.dropout', 'Dropout', (('inplace', False), ('p', 0.0), ('training', False))), ('dropout2', 'torch.nn.modules.dropout', 'Dropout', (('inplace', False), ('p', 0.0), ('training', False))))
    frozen_buffers = {}
    source_modes = (('', False), ('self_attn', False), ('self_attn.out_proj', False), ('linear1', False), ('dropout', False), ('linear2', False), ('norm1', False), ('norm2', False), ('dropout1', False), ('dropout2', False))
    input_specs = (TensorSpec((2, 3, 8), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_5: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_5', torch.tensor(
            [8, 9, 10, 11, 12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_7: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_7', torch.tensor(
            [16, 17, 18, 19, 20, 21, 22, 23],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_10: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_10', torch.tensor(
            [0, 1, 2, 3, 4, 5, 6, 7],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_12: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_12', torch.tensor(
            [8, 9, 10, 11, 12, 13, 14, 15],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_14: shape=(8,), dtype=torch.int64
        self.register_buffer('constant_14', torch.tensor(
            [16, 17, 18, 19, 20, 21, 22, 23],
            dtype=torch.int64, device='cpu').reshape((8,)))
        # constant_35: shape=(), dtype=torch.float64
        self.register_buffer('constant_35', torch.tensor(
            0.5,
            dtype=torch.float64, device='cpu').reshape(()))

    @property
    def param_self_attn_in_proj_weight(self):
        return self.source.self_attn.in_proj_weight

    @property
    def param_self_attn_in_proj_bias(self):
        return self.source.self_attn.in_proj_bias

    @property
    def param_self_attn_out_proj_weight(self):
        return self.source.self_attn.out_proj.weight

    @property
    def param_self_attn_out_proj_bias(self):
        return self.source.self_attn.out_proj.bias

    @property
    def param_norm1_weight(self):
        return self.source.norm1.weight

    @property
    def param_norm1_bias(self):
        return self.source.norm1.bias

    @property
    def param_linear1_weight(self):
        return self.source.linear1.weight

    @property
    def param_linear1_bias(self):
        return self.source.linear1.bias

    @property
    def param_linear2_weight(self):
        return self.source.linear2.weight

    @property
    def param_linear2_bias(self):
        return self.source.linear2.bias

    @property
    def param_norm2_weight(self):
        return self.source.norm2.weight

    @property
    def param_norm2_bias(self):
        return self.source.norm2.bias


class TransformerEncoderLayer(ExpandedModule):
    definition_type = TransformerEncoderLayerParameterDefinition

    def forward(self, x):
        # ROUTE -> (8, 8)
        node_1 = d.route(self.p.param_self_attn_in_proj_weight, self.p.constant_3, dim=0)
        # ROUTE -> (8, 8)
        node_4 = d.route(self.p.param_self_attn_in_proj_weight, self.p.constant_5, dim=0)
        # ROUTE -> (8, 8)
        node_6 = d.route(self.p.param_self_attn_in_proj_weight, self.p.constant_7, dim=0)
        # ROUTE -> (8,)
        node_8 = d.route(self.p.param_self_attn_in_proj_bias, self.p.constant_10, dim=0)
        # ROUTE -> (8,)
        node_11 = d.route(self.p.param_self_attn_in_proj_bias, self.p.constant_12, dim=0)
        # ROUTE -> (8,)
        node_13 = d.route(self.p.param_self_attn_in_proj_bias, self.p.constant_14, dim=0)
        # PERMUTE -> (8, 8)
        node_15 = d.permute(node_1, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_16 = d.project(x, node_15)
        # BROADCAST -> (2, 3, 8)
        node_17 = d.broadcast(node_8, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_18 = d.add(node_16, node_17)
        # PERMUTE -> (8, 8)
        node_19 = d.permute(node_4, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_20 = d.project(x, node_19)
        # BROADCAST -> (2, 3, 8)
        node_21 = d.broadcast(node_11, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_22 = d.add(node_20, node_21)
        # PERMUTE -> (8, 8)
        node_23 = d.permute(node_6, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_24 = d.project(x, node_23)
        # BROADCAST -> (2, 3, 8)
        node_25 = d.broadcast(node_13, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_26 = d.add(node_24, node_25)
        # RESHAPE -> (2, 3, 2, 4)
        node_27 = d.reshape(node_18, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_28 = d.permute(node_27, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 2, 4)
        node_29 = d.reshape(node_22, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_30 = d.permute(node_29, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 2, 4)
        node_31 = d.reshape(node_26, (2, 3, 2, 4))
        # PERMUTE -> (2, 2, 3, 4)
        node_32 = d.permute(node_31, (0, 2, 1, 3))
        # COMPARE -> (2, 2, 3, 3)
        node_33 = d.compare(node_28, node_30)
        # BROADCAST -> (2, 2, 3, 3)
        node_34 = d.broadcast(self.p.constant_35, (2, 2, 3, 3))
        # MUL -> (2, 2, 3, 3)
        node_36 = d.mul(node_33, node_34)
        # NORMALIZE -> (2, 2, 3, 3)
        node_37 = d.normalize(node_36)
        # MIX -> (2, 2, 3, 4)
        node_38 = d.mix(node_32, node_37)
        # PERMUTE -> (2, 3, 2, 4)
        node_39 = d.permute(node_38, (0, 2, 1, 3))
        # RESHAPE -> (2, 3, 8)
        node_40 = d.reshape(node_39, (2, 3, 8))
        # PERMUTE -> (8, 8)
        node_41 = d.permute(self.p.param_self_attn_out_proj_weight, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_43 = d.project(node_40, node_41)
        # BROADCAST -> (2, 3, 8)
        node_44 = d.broadcast(self.p.param_self_attn_out_proj_bias, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_46 = d.add(node_43, node_44)
        # REDUCE -> (2, 3, 3)
        node_47 = d.reduce(node_37, dim=1, reducer='mean')
        # ADD -> (2, 3, 8)
        node_48 = d.add(x, node_46)
        # NORM -> (2, 3, 8)
        node_49 = d.norm(node_48, normalized_shape=(8,), weight=self.p.param_norm1_weight, bias=self.p.param_norm1_bias, eps=1e-05)
        # PERMUTE -> (8, 12)
        node_52 = d.permute(self.p.param_linear1_weight, (1, 0))
        # PROJECT -> (2, 3, 12)
        node_54 = d.project(node_49, node_52)
        # BROADCAST -> (2, 3, 12)
        node_55 = d.broadcast(self.p.param_linear1_bias, (2, 3, 12))
        # ADD -> (2, 3, 12)
        node_57 = d.add(node_54, node_55)
        # NONLINEAR -> (2, 3, 12)
        node_58 = d.nonlinear(node_57)
        # PERMUTE -> (12, 8)
        node_59 = d.permute(self.p.param_linear2_weight, (1, 0))
        # PROJECT -> (2, 3, 8)
        node_61 = d.project(node_58, node_59)
        # BROADCAST -> (2, 3, 8)
        node_62 = d.broadcast(self.p.param_linear2_bias, (2, 3, 8))
        # ADD -> (2, 3, 8)
        node_64 = d.add(node_61, node_62)
        # ADD -> (2, 3, 8)
        node_65 = d.add(node_49, node_64)
        # NORM -> (2, 3, 8)
        node_66 = d.norm(node_65, normalized_shape=(8,), weight=self.p.param_norm2_weight, bias=self.p.param_norm2_bias, eps=1e-05)
        return node_66
