"""Unflatten: expanded primitive implementation for Unflatten.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class UnflattenParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Unflatten'
    source_repr = 'Unflatten(dim=1, unflattened_size=(3, 4))'
    source_configuration = (('', 'torch.nn.modules.flatten', 'Unflatten', (('dim', 1), ('training', True), ('unflattened_size', (3, 4)))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 12), torch.float64, torch.device('cpu')),)
    stateless = False


class Unflatten(ExpandedModule):
    definition_type = UnflattenParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 4)
        node_1 = d.reshape(x, (2, 3, 4))
        return node_1
