"""Unfold: expanded primitive implementation for Unfold.

Configuration: See source_repr and input_specs.
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class UnfoldParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Unfold'
    source_repr = 'Unfold(kernel_size=(2, 3), dilation=1, padding=1, stride=2)'
    source_configuration = (('', 'torch.nn.modules.fold', 'Unfold', (('dilation', 1), ('kernel_size', (2, 3)), ('padding', 1), ('stride', 2), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4, 5), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(54,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [-1, -1, -1, -1, 6, 8, -1, 16, 18, -1, -1, -1, 5, 7, 9, 15, 17, 19, -1, -1, -1, 6, 8, -1,
             16, 18, -1, -1, 1, 3, -1, 11, 13, -1, -1, -1, 0, 2, 4, 10, 12, 14, -1, -1, -1, 1, 3, -1,
             11, 13, -1, -1, -1, -1],
            dtype=torch.int64, device='cpu').reshape((54,)))


class Unfold(ExpandedModule):
    definition_type = UnfoldParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 20)
        node_1 = d.reshape(x, (2, 3, -1))
        # ROUTE -> (2, 3, 54)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # RESHAPE -> (2, 18, 9)
        node_4 = d.reshape(node_2, (2, 18, 9))
        return node_4
