"""Upsample: expanded primitive implementation for Upsample.

Configuration: fixed output size, nearest or bilinear; no antialias
Limitations: Static interpolation stencil, not grid_sample or data-dependent resampling.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class UpsampleParameterDefinition(ExpandedParameterDefinition):
    public_name = 'Upsample'
    source_repr = "Upsample(size=(6, 7), mode='bilinear')"
    source_configuration = (('', 'torch.nn.modules.upsampling', 'Upsample', (('align_corners', False), ('mode', 'bilinear'), ('name', 'Upsample'), ('recompute_scale_factor', None), ('scale_factor', None), ('size', (6, 7)), ('training', True))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 3, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(6, 3), dtype=torch.float64
        self.register_buffer('constant_3', torch.tensor(
            [[1.0, 0.0, 0.0], [0.75, 0.25, 0.0], [0.25, 0.75, 0.0], [0.0, 0.75, 0.25],
             [0.0, 0.25, 0.75], [0.0, 0.0, 1.0]],
            dtype=torch.float64, device='cpu').reshape((6, 3)))
        # constant_8: shape=(7, 4), dtype=torch.float64
        self.register_buffer('constant_8', torch.tensor(
            [[1.0, 0.0, 0.0, 0.0], [0.6428571428571429, 0.3571428571428571, 0.0, 0.0],
             [0.0714285714285714, 0.9285714285714286, 0.0, 0.0], [0.0, 0.5, 0.5, 0.0],
             [0.0, 0.0, 0.9285714285714284, 0.07142857142857162],
             [0.0, 0.0, 0.3571428571428572, 0.6428571428571428], [0.0, 0.0, 0.0, 1.0]],
            dtype=torch.float64, device='cpu').reshape((7, 4)))


class Upsample(ExpandedModule):
    definition_type = UpsampleParameterDefinition

    def forward(self, x):
        # PERMUTE -> (2, 3, 4, 3)
        node_1 = d.permute(x, (0, 1, 3, 2))
        # PERMUTE -> (3, 6)
        node_2 = d.permute(self.p.constant_3, (1, 0))
        # PROJECT -> (2, 3, 4, 6)
        node_4 = d.project(node_1, node_2)
        # PERMUTE -> (2, 3, 6, 4)
        node_5 = d.permute(node_4, (0, 1, 3, 2))
        # PERMUTE -> (2, 3, 6, 4)
        node_6 = d.permute(node_5, (0, 1, 2, 3))
        # PERMUTE -> (4, 7)
        node_7 = d.permute(self.p.constant_8, (1, 0))
        # PROJECT -> (2, 3, 6, 7)
        node_9 = d.project(node_6, node_7)
        # PERMUTE -> (2, 3, 6, 7)
        node_10 = d.permute(node_9, (0, 1, 2, 3))
        return node_10
