"""ZeroPad3d: expanded primitive implementation for ZeroPad3d.

Configuration: asymmetric positive padding (1,2) per axis
Limitations: Fixture configuration only; not complete PyTorch API parity.
Generated by python -m dsl_nn.expand. Editable review source.
Forward contains direct matrix_dsl operations, not a graph interpreter.
Static loops/helpers are expanded; SCAN bodies are explicit methods.
ParameterDefinition holds live parameters and literal constants.
"""
from __future__ import annotations
import torch
import matrix_dsl as d
from ..graph import TensorSpec
from ._support import ExpandedModule, ExpandedParameterDefinition


class ZeroPad3dParameterDefinition(ExpandedParameterDefinition):
    public_name = 'ZeroPad3d'
    source_repr = 'ZeroPad3d((1, 2, 1, 2, 1, 2))'
    source_configuration = (('', 'torch.nn.modules.padding', 'ZeroPad3d', (('padding', (1, 2, 1, 2, 1, 2)), ('training', True), ('value', 0.0))),)
    frozen_buffers = {}
    source_modes = (('', True),)
    input_specs = (TensorSpec((2, 3, 4, 4, 4), torch.float64, torch.device('cpu')),)
    stateless = False

    def __init__(self, source):
        super().__init__(source)
        # constant_3: shape=(343,), dtype=torch.int64
        self.register_buffer('constant_3', torch.tensor(
            [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 2, 3, -1, -1, -1, 4, 5, 6, 7,
             -1, -1, -1, 8, 9, 10, 11, -1, -1, -1, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, 17, 18, 19, -1, -1, -1,
             20, 21, 22, 23, -1, -1, -1, 24, 25, 26, 27, -1, -1, -1, 28, 29, 30, 31, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 32, 33,
             34, 35, -1, -1, -1, 36, 37, 38, 39, -1, -1, -1, 40, 41, 42, 43, -1, -1, -1, 44, 45, 46,
             47, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, 48, 49, 50, 51, -1, -1, -1, 52, 53, 54, 55, -1, -1, -1, 56, 57, 58, 59, -1,
             -1, -1, 60, 61, 62, 63, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            dtype=torch.int64, device='cpu').reshape((343,)))


class ZeroPad3d(ExpandedModule):
    definition_type = ZeroPad3dParameterDefinition

    def forward(self, x):
        # RESHAPE -> (2, 3, 64)
        node_1 = d.reshape(x, (2, 3, 64))
        # ROUTE -> (2, 3, 343)
        node_2 = d.route(node_1, self.p.constant_3, dim=-1, padding='zero')
        # RESHAPE -> (2, 3, 7, 7, 7)
        node_4 = d.reshape(node_2, (2, 3, 7, 7, 7))
        return node_4
